Repository shopgate/pwa, pull requests merged in 2018-10, with the labels that each got.

#289 Moved out the benchmarking tool out from devDependencies to the dependency list
  libraries/common/package.json
Labels: PR: Bug Fix :bug:

#293 Removed country codes from province province codes used by the form builder
  libraries/ui-shared/Form/Builder/iso-3166-2.js
Labels: PR: Bug Fix :bug:

#291 Implemented the EmbeddedMedia collection to improve handling of playing media on navigation
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/EmbeddedMedia.spec.js
  libraries/common/collections/index.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/collections/media-providers/YouTube.js
  libraries/common/collections/media-providers/YouTube.spec.js
  libraries/common/collections/media-providers/index.js
  libraries/common/helpers/html/handleDOM.js
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/app.spec.js
  themes/theme-gmd/.gitignore
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
Labels: PR: New Feature :rocket:

#302 Fixed hammer.js by fixing the version to 0.5.6
  libraries/commerce/package.json
  libraries/common/package-lock.json
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#303 Fixed filter attribute deselection from within the filters page
  themes/theme-gmd/pages/Filter/components/Content/index.jsx
Labels: PR: Bug Fix :bug:

#304 fixed a typo in a translation
  themes/theme-gmd/locale/en-US.json
Labels: PR: Polish :nail_care:

#300 clientInformation is taken from window.navigator instead of webStorage
  __mocks__/detector.js
  libraries/common/actions/client/fetchClientInformation.js
  libraries/common/package.json
  libraries/common/reducers/client/index.js
  libraries/core/helpers/version.js
  libraries/core/helpers/version.spec.js
  libraries/tracking/subscriptions/setup.js
  package.json
  yarn.lock
Labels: PR: Polish :nail_care:

#306 Fixed handling of deeplinks and push messages
  jest.config.js
  libraries/commerce/cart/constants/index.js
  libraries/commerce/cart/streams/index.js
  libraries/commerce/cart/streams/index.spec.js
  libraries/commerce/cart/subscriptions/index.js
  libraries/commerce/cart/subscriptions/index.spec.js
  libraries/common/action-creators/history/index.js
  libraries/common/action-creators/history/spec.js
  libraries/common/action-creators/index.js
  libraries/common/actions/app/handleLink.js
  libraries/common/actions/app/handleLink.spec.js
  libraries/common/actions/app/registerLinkEvents.js
  libraries/common/collections/AuthRoutes.js
  libraries/common/collections/AuthRoutes.spec.js
  libraries/common/collections/Redirects.js
  libraries/common/collections/Redirects.spec.js
  libraries/common/constants/ActionTypes.js
  libraries/common/streams/history.js
  libraries/common/streams/index.js
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/common/subscriptions/helpers/handleLinks.spec.js
  libraries/common/subscriptions/router.js
  libraries/tracking/streams/specHelper.js
Labels: PR: Bug Fix :bug:

#308 Overlapping selected filters are cut off by an ellipsis on the filter page.
  themes/theme-gmd/pages/Filter/components/Content/components/Selector/components/Selected/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Filter/components/Content/components/Selector/components/Selected/index.jsx
  themes/theme-gmd/pages/Filter/components/Content/components/Selector/components/Selected/style.js
  themes/theme-gmd/pages/Filter/components/Content/components/Selector/components/Toggle/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Filter/components/Content/components/Selector/components/Toggle/style.js
Labels: PR: Bug Fix :bug:

#311 Sorting does not request products
  __mocks__/@virtuous/react-conductor/Router/context.js
  libraries/commerce/search/actions/getSearchResults.js
  libraries/ui-material/Accordion/spec.jsx
  themes/theme-gmd/components/FilterBar/components/Content/components/FilterButton/index.jsx
  themes/theme-gmd/components/FilterBar/components/Content/components/Sort/connector.js
  themes/theme-gmd/components/FilterBar/components/Content/components/Sort/index.jsx
  themes/theme-gmd/pages/Cart/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Category/components/Bar/index.jsx
  themes/theme-gmd/pages/Category/components/Bar/spec.jsx
  themes/theme-gmd/pages/Category/subscriptions.spec.js
  themes/theme-gmd/pages/Search/components/Products/connector.js
  themes/theme-gmd/pages/Search/index.jsx
  themes/theme-gmd/pages/Search/subscriptions.js
Labels: PR: Bug Fix :bug:

#312 The checkout bar is only disabled once when the cart is busy.
  libraries/commerce/cart/subscriptions/index.js
  libraries/core/classes/BrowserConnector/index.js
Labels: PR: Bug Fix :bug:

#298 Changed test IDs and tests to not depend on exact same data and be able to run with similar data.
  libraries/common/components/List/components/Item/index.jsx
  themes/theme-gmd/components/CategoryList/index.jsx
  themes/theme-gmd/components/List/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/List/components/Item/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/List/components/Item/index.jsx
  themes/theme-gmd/components/List/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-gmd/e2e/elements/de.js
  themes/theme-gmd/e2e/helper/coupon.js
  themes/theme-gmd/e2e/integration/consistency/CartPage.js
  themes/theme-gmd/e2e/integration/consistency/CategoryPage.js
  themes/theme-gmd/e2e/integration/consistency/FavoritesPage.js
  themes/theme-gmd/e2e/integration/consistency/FilterPage.js
  themes/theme-gmd/e2e/integration/consistency/LoginPage.js
  themes/theme-gmd/e2e/integration/consistency/NavDrawer.js
  themes/theme-gmd/e2e/integration/consistency/ProductPage.js
  themes/theme-gmd/e2e/integration/consistency/ProductPageBasePrice.js
  themes/theme-gmd/e2e/integration/consistency/ProductPageOptions.js
  themes/theme-gmd/e2e/integration/consistency/ReviewsPage.js
  themes/theme-gmd/e2e/integration/consistency/SearchPage.js
  themes/theme-gmd/e2e/integration/consistency/StartPage.js
  themes/theme-gmd/e2e/integration/functional/CartPage.js
  themes/theme-gmd/e2e/integration/functional/CartPageOptions.js
  themes/theme-gmd/e2e/integration/functional/CategoryPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-gmd/e2e/integration/functional/FilterPage.js
  themes/theme-gmd/e2e/integration/functional/LoginPage.js
  themes/theme-gmd/e2e/integration/functional/ProductPage.js
  themes/theme-gmd/e2e/integration/functional/ProductPageOptions.js
  themes/theme-gmd/e2e/integration/functional/SearchPage.js
  themes/theme-gmd/e2e/integration/functional/StartPage.js
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/components/Title/index.jsx
  themes/theme-gmd/pages/Filter/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/FilterAttribute/components/MultiSelect/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/FilterAttribute/components/SingleSelect/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Description/index.jsx
  themes/theme-gmd/pages/Product/components/VariantSelects/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/CategoryList/index.jsx
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/index.jsx
  themes/theme-ios11/components/List/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Filter/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/FilterAttribute/components/MultiSelect/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/FilterAttribute/components/SingleSelect/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
Labels: PR: Internal :house:

#307 User is shown a white page when navigating
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Filter/components/Content/index.jsx
  yarn.lock
Labels: PR: Bug Fix :bug:

#313 Moved from @shopgate/react-hammerjs to react-hammerjs from npm.
  libraries/commerce/package.json
  libraries/common/components/ZoomPanContainer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Product/components/ImageSlider/index.jsx
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Product/components/ImageSlider/index.jsx
  yarn.lock
Labels: PR: Bug Fix :bug:

#295 Fix UI separating line between coupon and coupon field.
  themes/theme-gmd/pages/Cart/components/Item/components/Coupon/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Coupon/index.jsx
Labels: PR: Bug Fix :bug:

#314 Review props are not causing unnecessary updates in the component.
  themes/theme-gmd/components/AppBar/presets/BackBar/index.jsx
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/components/FormButtons/connector.js
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/connector.js
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/index.jsx
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/spec.jsx
  themes/theme-gmd/pages/WriteReview/index.jsx
  themes/theme-gmd/providers/View/index.jsx
  yarn.lock
Labels: PR: Bug Fix :bug:, PR: Polish :nail_care:

#316 Client Information now displays correctly inside NavDrawer
  libraries/ui-shared/ClientInformation/connector.js
Labels: PR: Bug Fix :bug:

#310 A getProductRelations pipeline redux implementation
  libraries/commerce/product/action-creators/errorProductRelations.js
  libraries/commerce/product/action-creators/receiveProductRelations.js
  libraries/commerce/product/action-creators/requestProductRelations.js
  libraries/commerce/product/actions/getProductRelations.js
  libraries/commerce/product/constants/Pipelines.js
  libraries/commerce/product/constants/index.js
  libraries/commerce/product/helpers/index.js
  libraries/commerce/product/reducers/index.js
  libraries/commerce/product/reducers/productRelationsByHash.js
  libraries/commerce/product/selectors/relations.js
  libraries/commerce/product/selectors/relations.spec.js
  libraries/commerce/product/streams/index.js
  libraries/commerce/product/subscriptions/index.js
  libraries/commerce/product/subscriptions/index.spec.js
Labels: PR: New Feature :rocket:

#317 Changed Makefile to support subtrees and prepare it for additional automation
  Makefile
Labels: PR: Internal :house:

#319 Fixed a broken import
  libraries/commerce/product/helpers/index.js
Labels: PR: Bug Fix :bug:

#320 Products are now requested with the exact price range from the filters
  .eslintignore
  libraries/common/components/Backdrop/__snapshots__/spec.jsx.snap
  libraries/ui-material/NavDrawer/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Dialog/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Sheet/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Filter/components/Content/helpers/buildUpdatedFilters.js
  themes/theme-gmd/pages/Filter/components/Content/helpers/buildUpdatedFilters.spec.js
  themes/theme-gmd/pages/Filter/components/Content/index.jsx
Labels: bug

#318 Filters are now taken from the action when requesting
  themes/theme-gmd/pages/Category/subscriptions.js
Labels: bug

#321 The store is not re-hydrated after the initial state was already set.
  libraries/common/package.json
  libraries/common/reducers/page/index.js
  libraries/common/store/index.js
  yarn.lock
Labels: bug

#322 Added BackBar to all iOS pages expect for the Startpage and the Login.
  libraries/common/reducers/client/index.js
  libraries/common/styles/reset/root.js
  package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Cart/components/Content/index.jsx
  themes/theme-ios11/pages/Category/components/AppBar/index.jsx
  themes/theme-ios11/pages/Favorites/index.jsx
  themes/theme-ios11/pages/Page/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/AppBar/index.jsx
  themes/theme-ios11/pages/RootCategory/index.jsx
  themes/theme-ios11/pages/Search/components/Content/index.jsx
Labels: enhancement

#323 Removed the CartButton from the default AppBar in the iOS theme.
  themes/theme-gmd/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-gmd/widgets/Liveshopping/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartBadge/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartBadge/style.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartButton/connector.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartButton/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartButton/style.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/components/CartButton/transition.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/jest.config.js
  themes/theme-ios11/styles/index.js
  themes/theme-ios11/widgets/Liveshopping/index.jsx
Labels: enhancement

#315 Fix product price in favorites to match product actual price
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/spec.jsx
  themes/theme-gmd/pages/Favorites/mock.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/spec.jsx
  themes/theme-ios11/pages/Favorites/mock.js
Labels: bug

#328 Added default limit for getProductsRelations action
  libraries/commerce/product/actions/getProductRelations.js
Labels: bug

#333 CartButton and SearchButton are now reliably hidden on cart page
  themes/theme-gmd/pages/subscribers.js
Labels: bug

#330 Added an action that allows to disable/enable the login form
  libraries/common/action-creators/user/index.js
  libraries/common/constants/ActionTypes.js
  libraries/common/reducers/user/login.js
  libraries/common/selectors/user.js
  themes/theme-gmd/pages/Login/connector.js
  themes/theme-gmd/pages/Login/index.jsx
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/connector.js
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/index.jsx
  themes/theme-ios11/pages/More/mock.js
Labels: enhancement

#331 The browser connector is used only in none SDK web environments.
  libraries/core/classes/AppCommand/index.js
  libraries/core/classes/AppCommand/spec.js
  libraries/core/classes/BrowserConnector/index.js
  libraries/core/helpers/index.js
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/extension-config.json
Labels: enhancement

#325 Added iOS style AddToCart bar.
  libraries/ui-shared/AddToCartButton/__snapshots__/spec.jsx.snap
  libraries/ui-shared/AddToCartButton/index.jsx
  themes/theme-ios11/components/FilterBar/components/Content/components/FilterButton/style.js
  themes/theme-ios11/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/AddToCartBar/actions.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/actions.spec.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddMoreButton/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddMoreButton/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddToCartButton/connector.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddToCartButton/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddToCartButton/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/CartItemsCount/components/Count/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/CartItemsCount/components/Count/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/CartItemsCount/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/CartItemsCount/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/constants.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/mock.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/subscriptions.js
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/components/Icon/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/components/Icon/style.js
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/components/Icon/transition.js
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/injector.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/components/CartButton/style.js
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-ios11/pages/subscribers.js
Labels: enhancement

#336 Applied iOS styling to products cards and product grid items of the iOS theme.
  libraries/common/helpers/config/mock.js
  libraries/ui-shared/Card/style.js
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/components/ProductCard/style.js
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/style.js
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDiscount/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDiscount/style.js
  themes/theme-ios11/components/ProductGrid/components/Item/style.js
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
  themes/theme-ios11/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/components/ProductGridPrice/index.jsx
  themes/theme-ios11/components/ProductGridPrice/style.js
  themes/theme-ios11/components/ProductImage/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductImage/index.jsx
  themes/theme-ios11/components/ProductImage/style.js
  themes/theme-ios11/pages/Category/index.jsx
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Liveshopping/index.jsx
  themes/theme-ios11/widgets/Liveshopping/style.js
  themes/theme-ios11/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/style.js
Labels: enhancement

#338 Introduced automatic creation of github releases
  Makefile
Labels: enhancement

#342 Makefile improvements
  Makefile
Labels: enhancement

#345 Fixed AppCommand lib version checks
  Makefile
  libraries/core/helpers/version.js
  libraries/core/helpers/version.spec.js
Labels: bug

#339 Split availability text and stock information on product details page.
  libraries/commerce/product/constants/Portals.js
  scripts/check-release-version.js
  themes/theme-gmd/pages/Product/components/Header/components/Availability/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/StockInfo/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/StockInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/StockInfo/style.js
  themes/theme-gmd/pages/Product/components/Header/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Availability/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/StockInfo/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/StockInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/StockInfo/style.js
  themes/theme-ios11/pages/Product/components/Header/index.jsx
Labels: bug

#341 Removed NavDrawer in iOS
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/components/NavDrawer/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/NavDrawer/components/CartButton/components/Badge/connector.js
  themes/theme-ios11/components/NavDrawer/components/CartButton/components/Badge/index.jsx
  themes/theme-ios11/components/NavDrawer/components/CartButton/components/Badge/style.js
  themes/theme-ios11/components/NavDrawer/components/CartButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/CategoryButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/FavoritesButton/components/Badge/connector.js
  themes/theme-ios11/components/NavDrawer/components/FavoritesButton/components/Badge/index.jsx
  themes/theme-ios11/components/NavDrawer/components/FavoritesButton/components/Badge/style.js
  themes/theme-ios11/components/NavDrawer/components/FavoritesButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/Header/connector.js
  themes/theme-ios11/components/NavDrawer/components/Header/index.jsx
  themes/theme-ios11/components/NavDrawer/components/Header/style.js
  themes/theme-ios11/components/NavDrawer/components/HomeButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/ImprintButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/LogoutButton/connector.js
  themes/theme-ios11/components/NavDrawer/components/LogoutButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/PaymentButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/PrivacyButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/QuickLinks/connector.js
  themes/theme-ios11/components/NavDrawer/components/QuickLinks/index.jsx
  themes/theme-ios11/components/NavDrawer/components/ReturnsButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/ShippingButton/index.jsx
  themes/theme-ios11/components/NavDrawer/components/SubHeader/index.jsx
  themes/theme-ios11/components/NavDrawer/components/SubHeader/style.js
  themes/theme-ios11/components/NavDrawer/components/TermsButton/index.jsx
  themes/theme-ios11/components/NavDrawer/connector.js
  themes/theme-ios11/components/NavDrawer/constants.js
  themes/theme-ios11/components/NavDrawer/index.jsx
  themes/theme-ios11/components/NavDrawer/selectors.js
  themes/theme-ios11/components/NavDrawer/spec.jsx
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/pages/Page/components/Content/index.jsx
Labels: enhancement

#346 Changed Viewport to split TabBar and content into 2 sections
  libraries/ui-material/SnackBar/style.js
  libraries/ui-material/SnackBar/transition.js
  themes/theme-ios11/components/TabBar/style.js
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/components/Viewport/style.js
  themes/theme-ios11/index.jsx
  themes/theme-ios11/pages/Page/components/Content/index.jsx
  themes/theme-ios11/pages/Page/components/Content/style.js
  themes/theme-ios11/styles/index.js
  themes/theme-ios11/styles/routes.js
Labels: bug

#332 Implemented iOS and Android Share icons and Native Share App Command
  libraries/core/commands/shareItem.js
  libraries/ui-ios/icons/ShareIcon.jsx
  libraries/ui-material/icons/ShareIcon.jsx
Labels: enhancement

#340 Remove continue shopping button in iOS
  libraries/ui-ios/AppBar/index.jsx
  themes/theme-ios11/components/TabBar/subscriptions.js
  themes/theme-ios11/components/TabBar/subscriptions.spec.js
  themes/theme-ios11/pages/Cart/components/Empty/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/Empty/connector.js
  themes/theme-ios11/pages/Cart/components/Empty/index.jsx
  themes/theme-ios11/pages/Cart/components/Empty/spec.jsx
  themes/theme-ios11/pages/Cart/components/Empty/style.js
  themes/theme-ios11/pages/Favorites/components/EmptyFavorites/components/ContinueButton/connector.js
  themes/theme-ios11/pages/Favorites/components/EmptyFavorites/components/ContinueButton/index.jsx
  themes/theme-ios11/pages/Favorites/components/EmptyFavorites/components/ContinueButton/style.js
  themes/theme-ios11/pages/Favorites/components/EmptyFavorites/index.jsx
  themes/theme-ios11/theme-config.js
Labels: enhancement
