Repository shopgate/pwa, pull requests merged in 2018-09, with the labels that each got.

#246 Pwa 922 refactor filter chips
  libraries/ui-shared/Chip/index.jsx
  libraries/ui-shared/Chip/style.js
Labels: enhancement

#248 PWA-945 Updated conductor
  libraries/common/package.json
  yarn.lock
Labels: enhancement

#279 Portals: Sending original component down to the portal instance.
  libraries/common/components/Portal/index.jsx
Labels: PR: New Feature :rocket:

#278 Added Pull Request Template and automatic changelog creation.
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  lerna.json
Labels: PR: New Feature :rocket:

#287 Added iPhoneXs, XsMax and Xr support
  libraries/common/constants/Device.js
Labels: PR: Bug Fix :bug:
