Repository shopgate/pwa, pull requests merged in 2018-11, with the labels that each got.

#357 AddToCartBar is now rendered outside of the page content
  themes/theme-ios11/components/TabBar/style.js
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/components/Viewport/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/style.js
Labels: bug

#361 Corrected visual bugs inside GMD
  themes/theme-gmd/components/Viewport/style.js
  themes/theme-gmd/theme-config.js
Labels: bug

#362 CartButton style adjustments
  themes/theme-ios11/components/AppBar/components/CartButton/components/CartBadge/style.js
  themes/theme-ios11/components/AppBar/components/CartButton/index.jsx
Labels: enhancement

#354 Removed inline scroll polyfill in favour of the npm package
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/common/helpers/scrollPolyfill/index.js
  themes/theme-gmd/index.jsx
  themes/theme-gmd/package.json
  themes/theme-ios11/index.jsx
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#360 AppBar is now rendered outside of the scrollable content
  libraries/ui-ios/AppBar/index.jsx
  libraries/ui-ios/AppBar/style.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/components/FilterBar/components/Content/components/Sort/style.js
  themes/theme-ios11/components/View/components/Content/style.js
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/components/Viewport/style.js
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/style.js
  themes/theme-ios11/pages/Browse/components/SearchField/style.js
  themes/theme-ios11/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
Labels: bug

#358 iOS widget headline styling is now consistent
  themes/theme-ios11/components/Headline/style.js
  themes/theme-ios11/widgets/CategoryList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/CategoryList/index.jsx
  themes/theme-ios11/widgets/CategoryList/style.js
  themes/theme-ios11/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/index.jsx
  themes/theme-ios11/widgets/ProductSlider/spec.jsx
Labels: bug

#343 iOS More Route
  extensions/@shopgate-user-privacy/frontend/DeleteAccount/index.jsx
  libraries/common/components/Link/connector.js
  libraries/common/helpers/mocks/mockRenderOptions.js
  libraries/common/selectors/user.js
  themes/theme-gmd/components/NavDrawer/components/LogoutButton/index.jsx
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Item/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Item/index.jsx
  themes/theme-ios11/pages/More/components/Item/index.spec.jsx
  themes/theme-ios11/pages/More/components/Item/style.js
  themes/theme-ios11/pages/More/components/Quicklinks/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Quicklinks/connector.js
  themes/theme-ios11/pages/More/components/Quicklinks/index.jsx
  themes/theme-ios11/pages/More/components/Quicklinks/index.spec.jsx
  themes/theme-ios11/pages/More/components/Quicklinks/selectors.js
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedIn/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/connector.js
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/style.js
  themes/theme-ios11/pages/More/components/UserMenu/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/index.spec.jsx
  themes/theme-ios11/pages/More/connector.js
  themes/theme-ios11/pages/More/index.jsx
  themes/theme-ios11/pages/More/index.spec.jsx
  themes/theme-ios11/pages/More/style.js
  themes/theme-ios11/pages/index.jsx
  themes/theme-ios11/pages/routes.js
  themes/theme-ios11/widgets/Products/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Products/index.jsx
Labels: enhancement

#353 Fixed an issue where the page content was overlapped by footer components
  themes/theme-gmd/components/FilterBar/components/Content/components/FilterButton/style.js
  themes/theme-gmd/components/View/components/Below/index.jsx
  themes/theme-gmd/components/View/components/Content/index.jsx
  themes/theme-gmd/components/View/components/Content/style.js
  themes/theme-gmd/components/View/index.jsx
  themes/theme-gmd/pages/Cart/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/View/components/Below/index.jsx
  themes/theme-ios11/components/View/components/Content/index.jsx
  themes/theme-ios11/components/View/components/Content/style.js
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/pages/Cart/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddMoreButton/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/components/AddToCartButton/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/style.js
Labels: bug

#365 Corrected issue with native modals and images on iOS
  libraries/common/components/Image/__snapshots__/spec.jsx.snap
  libraries/common/components/Image/style.js
Labels: bug

#363 Updated `react-hot-loader` to prevent issues with newer `react` version.
  extensions/@shopgate-product-reviews/frontend/package.json
  package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#367 Fixed product list updates when filters where applied or changed
  libraries/commerce/search/actions/getSearchResults.js
  libraries/common/package.json
  libraries/common/selectors/router.js
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Category/subscriptions.js
  themes/theme-gmd/pages/Search/subscriptions.js
  themes/theme-gmd/pages/Search/subscriptions.spec.js
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Category/subscriptions.js
  themes/theme-ios11/pages/Search/components/Products/connector.js
  themes/theme-ios11/pages/Search/subscriptions.js
  themes/theme-ios11/pages/Search/subscriptions.spec.js
  yarn.lock
Labels: bug

#368 Corrected a bug where the filters labels can run out of the viewport
  themes/theme-gmd/pages/Filter/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Filter/components/ListItem/components/Label/style.js
  themes/theme-gmd/pages/Filter/components/ListItem/style.js
  themes/theme-gmd/pages/FilterAttribute/components/Item/index.jsx
  themes/theme-gmd/pages/FilterAttribute/components/Item/style.js
  themes/theme-gmd/pages/FilterAttribute/components/MultiSelect/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/FilterAttribute/components/SingleSelect/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Filter/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Filter/components/ListItem/components/Label/style.js
  themes/theme-ios11/pages/Filter/components/ListItem/style.js
  themes/theme-ios11/pages/FilterAttribute/components/Item/index.jsx
  themes/theme-ios11/pages/FilterAttribute/components/Item/style.js
  themes/theme-ios11/pages/FilterAttribute/components/MultiSelect/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/FilterAttribute/components/SingleSelect/__snapshots__/spec.jsx.snap
Labels: bug

#374 Forced the search input field to reset
  themes/theme-gmd/components/Search/index.jsx
Labels: bug

#371 Correct price formatting on product detail page when price is 0
  themes/theme-gmd/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Price/index.jsx
Labels: bug

#375 Correct bug where products could not be sorted due to wrong navigation location
  libraries/common/package.json
  themes/theme-gmd/components/FilterBar/components/Content/components/Sort/index.jsx
  themes/theme-gmd/package.json
  themes/theme-ios11/components/FilterBar/components/Content/components/Sort/index.jsx
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#379 Added the guest registration link to the legacy link list
  libraries/common/subscriptions/helpers/handleLinks.js
Labels: bug

#378 Corrected a bug where child product prices were not updating
  libraries/commerce/product/selectors/price.js
  libraries/ui-shared/Price/index.jsx
  themes/theme-gmd/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Price/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Price/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
Labels: bug

#370 Fixed an inAppBrowser issue where previous opened pages got visible again
  libraries/common/components/Router/helpers/parsed-link/actions.js
  libraries/common/components/Router/helpers/parsed-link/actions.spec.js
  libraries/common/components/Router/helpers/parsed-link/options.js
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/helpers/clearUpInAppBrowser.js
  libraries/common/subscriptions/helpers/clearUpInAppBrowser.spec.js
Labels: bug

#372 Fixed an inAppBrowser issue where previous opened pages got visible again
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/helpers/clearUpInAppBrowser.js
  libraries/common/subscriptions/helpers/clearUpInAppBrowser.spec.js
  libraries/common/subscriptions/helpers/handleLinks.js
Labels: bug

#383 Characteristic button text is now aligned on iOS
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/index.jsx
Labels: bug

#382 Corrected a bug that prevented filter attributes from being selected
  themes/theme-gmd/pages/Filter/components/Content/index.jsx
  themes/theme-ios11/pages/Filter/components/Content/index.jsx
Labels: bug

#377 Removed unnecessary white space below routes
  themes/theme-gmd/components/View/components/Above/index.jsx
  themes/theme-gmd/components/View/components/Below/index.jsx
  themes/theme-gmd/components/View/components/Content/index.jsx
  themes/theme-gmd/components/View/components/Content/style.js
  themes/theme-gmd/components/View/index.jsx
  themes/theme-gmd/pages/Cart/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/View/components/Above/index.jsx
  themes/theme-ios11/components/View/components/Below/index.jsx
  themes/theme-ios11/components/View/components/Content/index.jsx
  themes/theme-ios11/components/View/components/Content/style.js
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/pages/Cart/__snapshots__/spec.jsx.snap
Labels: bug

#385 Reverted styling changes to SnackBar
  libraries/ui-material/SnackBar/style.js
  libraries/ui-material/SnackBar/transition.js
Labels: bug

#386 Re-added hiding of the legacy menu bar on app start
  libraries/common/helpers/legacy/index.js
  libraries/common/helpers/legacy/index.spec.js
  libraries/common/subscriptions/app.js
Labels: bug

#391 Tapping on blank area now closes Search
  themes/theme-gmd/components/Search/components/Backdrop/index.jsx
  themes/theme-gmd/components/Search/components/Backdrop/style.js
  themes/theme-gmd/components/Search/components/Suggestions/components/Backdrop/index.jsx
  themes/theme-gmd/components/Search/components/Suggestions/index.jsx
  themes/theme-gmd/components/Search/index.jsx
  themes/theme-gmd/components/Search/style.js
Labels: bug

#393 Replaced deprecated FR, LV, FE and GE iso province codes
  libraries/ui-shared/Form/Builder/iso-3166-2.js
Labels: bug

#387 Added flushTab option for legacy links within the parsed-link helper
  libraries/common/components/Router/helpers/parsed-link/actions.js
  libraries/common/components/Router/helpers/parsed-link/options.js
Labels: bug

#388 Added flushTab option for legacy links within the handleLinks helper
  libraries/common/subscriptions/helpers/handleLinks.js
Labels: bug

#395 Fixed a bug that caused broken product pages
  themes/theme-gmd/pages/Product/components/ImageSlider/index.jsx
Labels: bug

#401 Updated conductor to 1.0.0-beta.45
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#403 More menu buttons on iOS will now wrap on small devices
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedOut/style.js
Labels: bug

#404 Improve concurrent cart actions, when adding a coupon from deeplink
  libraries/commerce/cart/actions/fetchCart.js
  libraries/commerce/cart/selectors/index.js
  libraries/commerce/cart/selectors/spec.js
  libraries/commerce/cart/subscriptions/index.js
Labels: bug

#406 Changed pipeline usage to match specification
  libraries/commerce/cart/actions/deleteProductsFromCart.js
  libraries/commerce/cart/actions/updateProductsInCart.js
  libraries/commerce/cart/reducers/index.js
Labels: enhancement

#408 Re-added hiding of the legacy menu bar on app start
  libraries/common/helpers/legacy/index.js
  libraries/common/helpers/legacy/index.spec.js
  libraries/common/subscriptions/app.js
  themes/theme-gmd/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
Labels: bug

#409 Cart items are not visible when entering the cart
  themes/theme-gmd/pages/Cart/components/Item/components/Product/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/index.jsx
Labels: bug

#411 Page content is now below all AppBars
  themes/theme-ios11/components/Viewport/style.js
Labels: bug

#381 Added portals and location prop for product-item.price
  libraries/commerce/category/constants/Portals.js
  themes/theme-gmd/components/ProductCard/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/index.jsx
  themes/theme-gmd/components/ProductList/components/Item/index.jsx
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/index.jsx
  themes/theme-ios11/components/ProductList/components/Item/index.jsx
Labels: enhancement

#410 Fixed a cached selector that caused outdated url in tracking data
  libraries/tracking/subscriptions/pages.js
  libraries/tracking/subscriptions/search.js
Labels: bug

#407 Fixed broken InfiniteContainer process
  libraries/common/components/InfiniteContainer/index.jsx
  libraries/common/components/InfiniteContainer/spec.jsx
  libraries/common/helpers/dom/index.js
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/index.jsx
  themes/theme-gmd/components/ProductGrid/spec.jsx
  themes/theme-gmd/components/ProductList/index.jsx
  themes/theme-gmd/components/View/components/Content/index.jsx
  themes/theme-gmd/components/View/index.jsx
  themes/theme-gmd/providers/View/index.jsx
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/index.jsx
  themes/theme-ios11/components/ProductGrid/spec.jsx
  themes/theme-ios11/components/ProductList/index.jsx
  themes/theme-ios11/components/View/components/Content/index.jsx
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/providers/View/index.jsx
Labels: bug

#405 Refactored SnackBar to use react-spring
  libraries/ui-material/SnackBar/index.jsx
  libraries/ui-material/SnackBar/transition.js
  libraries/ui-material/package.json
  themes/theme-gmd/components/Search/components/Suggestions/components/List/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/Search/components/Suggestions/components/List/style.js
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/style.js
  yarn.lock
Labels: bug

#415 Copied Viewport blocks to GMD
  libraries/ui-material/NavDrawer/style.js
  themes/theme-gmd/components/Viewport/index.jsx
  themes/theme-gmd/components/Viewport/style.js
  themes/theme-gmd/index.jsx
  themes/theme-gmd/styles/routes.js
Labels: bug, enhancement

#418 Updated Conductor package
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Product/components/ImageSlider/index.jsx
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Product/components/ImageSlider/index.jsx
  yarn.lock
Labels: bug

#419 Improved interaction with cart items and the coupon field
  themes/theme-gmd/pages/Cart/components/CouponField/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/CouponField/components/Layout/index.jsx
  themes/theme-gmd/pages/Cart/components/CouponField/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/components/Title/style.js
  themes/theme-gmd/pages/Cart/components/Item/components/Product/index.jsx
  themes/theme-ios11/pages/Cart/components/CouponField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/CouponField/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/CouponField/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/components/Title/style.js
  themes/theme-ios11/pages/Cart/components/Item/components/Product/index.jsx
Labels: bug, enhancement

#423 Increased AppBar z-index to avoid overlapping elements
  libraries/ui-material/AppBar/style.js
Labels: bug

#398 Fixed wrong displayed tier price products
  libraries/ui-shared/Price/index.jsx
  themes/theme-gmd/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/ProductGridPrice/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Price/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Price/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
Labels: bug

#428 Removed the Accordion height transition
  libraries/ui-material/Accordion/__snapshots__/spec.jsx.snap
  libraries/ui-material/Accordion/components/AccordionContent/__snapshots__/spec.jsx.snap
  libraries/ui-material/Accordion/components/AccordionContent/style.js
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/Browse/index.jsx
Labels: bug

#429 Changed the ViewContent to receive the visible flag as a prop
  themes/theme-ios11/components/View/components/Content/index.jsx
Labels: bug

#426 Empty filter page after the app was in the background for a while
  libraries/commerce/filter/actions/getFilters.js
  libraries/commerce/filter/actions/helpers/processParams.js
  themes/theme-gmd/pages/Filter/components/Content/index.jsx
  themes/theme-ios11/pages/Filter/components/Content/index.jsx
Labels: bug

#431 Cart information now wraps where appropriate
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/style.js
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/style.js
Labels: bug

#434 Updated conductor to v1.0.0 to address scroll issue
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#436 Removed non-memoized function call from connector
  themes/theme-ios11/components/TabBar/connector.js
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/components/TabBar/selectors.js
  themes/theme-ios11/components/TabBar/tabs.js
Labels: enhancement

#437 GMD Snackbar adjusts action color to white when accent color to black contrast is less than 4
  themes/theme-gmd/components/SnackBar/components/ActionButton/style.js
  themes/theme-gmd/components/SnackBar/constants.js
  themes/theme-gmd/components/SnackBar/style.js
Labels: bug

#438 Safe color contrast for toast action button
  libraries/ui-material/SnackBar/style.js
  libraries/ui-material/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#433 Added inset padding to Material AppBar. AppBar in GMD now renders outside of View content
  .travis.yml
  libraries/common/components/KeyboardConsumer/index.jsx
  libraries/common/subscriptions/app.js
  libraries/ui-material/AppBar/style.js
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-gmd/components/Search/components/Suggestions/index.jsx
  themes/theme-gmd/components/Search/components/Suggestions/style.js
  themes/theme-gmd/components/Search/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/style.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
Labels: enhancement
