Repository shopgate/pwa, pull requests merged in 2019-03, with the labels that each got.

#560 Make start page content load after window load event
  libraries/core/commands/hideSplashScreen.js
  libraries/core/commands/onload.js
  themes/theme-gmd/pages/StartPage/index.jsx
  themes/theme-ios11/pages/StartPage/index.jsx
Labels: bug

#564 Restructured PaymentBar and added Portals around cart totals
  libraries/commerce/cart/constants/Portals.js
  libraries/ui-shared/ActionButton/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/connector.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/connector.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/connector.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Label/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Label/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/TotalRow/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/TotalRow/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/totalsPortalProps.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/spec.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/connector.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Amount/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/connector.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/components/Label/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/connector.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Amount/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Label/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/components/Label/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/SubTotal/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/TotalRow/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/TotalRow/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/totalsPortalProps.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/spec.jsx
  yarn.lock
Labels: enhancement

#565 Add possibility to hide and replace the TabBar for the iOS theme
  libraries/common/collections/Configuration.js
  libraries/common/collections/index.js
  libraries/common/constants/Configuration.js
  themes/theme-ios11/components/TabBar/constants.js
  themes/theme-ios11/components/TabBar/helpers/getTabActionComponentForType.js
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/components/TabBar/style.js
  themes/theme-ios11/components/TabBar/subscriptions.js
  themes/theme-ios11/components/TabBar/subscriptions.spec.js
  themes/theme-ios11/themeApi/index.js
Labels: enhancement

#567 Add shop number back to localstorage key of redux store
  libraries/common/store/index.js
Labels: bug

#569 Fix navigation with special characters in search query
  themes/theme-gmd/components/Search/index.jsx
Labels: bug

#570 Show Barcode Scan results (basic)
  libraries/commerce/product/actions/fetchProductsByQuery.js
  libraries/commerce/product/helpers/index.js
  libraries/commerce/scanner/action-creators/index.js
  libraries/commerce/scanner/constants/index.js
  libraries/commerce/scanner/index.js
  libraries/commerce/scanner/streams/index.js
  libraries/commerce/scanner/subscriptions/index.js
  libraries/commerce/scanner/subscriptions/index.spec.js
  libraries/commerce/search/helpers/index.js
  libraries/core/constants/Scanner.js
  themes/theme-gmd/pages/subscribers.js
  themes/theme-ios11/pages/subscribers.js
Labels: enhancement

#572 The unused currentProduct reducer is removed from the default redux store.
  libraries/commerce/product/action-creators/resetCurrentProduct.js
  libraries/commerce/product/mock.js
  libraries/commerce/product/reducers/currentProduct.js
  libraries/commerce/product/reducers/index.js
  libraries/commerce/product/selectors/options.js
  libraries/commerce/product/selectors/price.js
  libraries/commerce/reviews/mock.js
  libraries/ui-shared/FavoritesButton/mock.js
  package.json
  themes/theme-gmd/components/Reviews/mock.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/mock.js
  themes/theme-gmd/pages/Product/components/Header/components/Shipping/mock.js
  themes/theme-gmd/pages/Product/components/mock.js
  themes/theme-ios11/components/Reviews/mock.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/mock.js
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/mock.js
  themes/theme-ios11/pages/Product/components/Header/components/Shipping/mock.js
  themes/theme-ios11/pages/Product/components/mock.js
Labels: enhancement

#574 Unused selectors for UI and toast messages have been removed.
  libraries/common/selectors/toast.js
  libraries/common/selectors/ui.js
Labels: enhancement

#575 The routeDidChange$ stream is now an alias of routeDidEnter$ since it is already deprecated.
  libraries/common/streams/router.js
Labels: bug

#576 Sentry.io level / severity is not send correctly
  libraries/common/subscriptions/error.js
  libraries/core/classes/ErrorManager/index.js
  libraries/core/classes/ErrorManager/spec.js
  libraries/core/constants/ErrorManager.js
Labels: bug

#573 Show QR Code Scan results
  libraries/commerce/category/actions/fetchCategory.js
  libraries/commerce/category/helpers/index.js
  libraries/commerce/category/index.js
  libraries/commerce/category/selectors/index.js
  libraries/commerce/product/actions/fetchProductsById.js
  libraries/commerce/scanner/actions/handleBarCode.js
  libraries/commerce/scanner/actions/handleBarCode.spec.js
  libraries/commerce/scanner/actions/handleQrCode.js
  libraries/commerce/scanner/actions/handleQrCode.spec.js
  libraries/commerce/scanner/constants/index.js
  libraries/commerce/scanner/helpers/index.js
  libraries/commerce/scanner/helpers/index.spec.js
  libraries/commerce/scanner/streams/index.spec.js
  libraries/commerce/scanner/subscriptions/index.js
  libraries/commerce/scanner/subscriptions/index.spec.js
  libraries/commerce/search/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
Labels: enhancement

#581 Added tracking for barcode scanner events
  libraries/commerce/scanner/action-creators/errorHandleScanner.js
  libraries/commerce/scanner/action-creators/scannerFinished.js
  libraries/commerce/scanner/action-creators/successHandleScanner.js
  libraries/commerce/scanner/actions/handleBarCode.js
  libraries/commerce/scanner/actions/handleBarCode.spec.js
  libraries/commerce/scanner/actions/handleQrCode.js
  libraries/commerce/scanner/actions/handleQrCode.spec.js
  libraries/commerce/scanner/constants/index.js
  libraries/commerce/scanner/streams/index.js
  libraries/commerce/scanner/streams/index.spec.js
  libraries/commerce/scanner/subscriptions/index.js
  libraries/commerce/scanner/subscriptions/index.spec.js
  libraries/common/helpers/data/spec.js
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/tracking/helpers/index.js
  libraries/tracking/helpers/index.spec.js
  libraries/tracking/streams/scanner.js
  libraries/tracking/streams/scanner.spec.js
  libraries/tracking/subscriptions/scanner.js
  libraries/tracking/subscriptions/scanner.spec.js
  themes/theme-gmd/pages/subscribers.js
  themes/theme-ios11/pages/subscribers.js
Labels: enhancement

#580 Open Scanner (basic)
  libraries/commerce/scanner/constants/Portals.js
  libraries/common/helpers/config/index.js
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/connector.js
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/spec.jsx
Labels: enhancement

#586 Added changelog starting from PWA version 6.0.0
  CHANGELOG.md
  lerna.json
  package.json
  themes/theme-gmd/CHANGELOG.md
  themes/theme-ios11/CHANGELOG.md
Labels: polish

#588 Add portals wrapping the View Content
  libraries/common/constants/Portals.js
  themes/theme-gmd/components/View/components/Content/index.jsx
  themes/theme-ios11/components/View/components/Content/index.jsx
Labels: enhancement
