Repository shopgate/pwa, pull requests merged in 2019-12, with the labels that each got.

#873 Changed the translation system to prevent the app from crashing for invalid translation messages.
  libraries/common/helpers/i18n/getTranslator.js
Labels: bug

#872 Added plotProjectsSetSegmentationProperties app command
  libraries/core/commands/__tests__/plotProjects.spec.js
  libraries/core/commands/plotProjects.js
Labels: enhancement

#874 Log generic errors to sentry
  libraries/common/subscriptions/error.js
Labels: internal

#869 The theme now provides the webpack configuration for the compilation process.
  .eslintignore
  Makefile
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-user-privacy/frontend/package.json
  libraries/commerce/package.json
  libraries/common/package.json
  libraries/core/package.json
  libraries/engage/package.json
  libraries/ui-ios/package.json
  libraries/ui-material/package.json
  libraries/ui-shared/package.json
  libraries/webcheckout/package.json
  package.json
  themes/theme-gmd/deps/recompose/index.js
  themes/theme-gmd/deps/recompose/package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/webpack.config.js
  themes/theme-ios11/deps/recompose/index.js
  themes/theme-ios11/deps/recompose/package.json
  themes/theme-ios11/package.json
  themes/theme-ios11/webpack.config.js
  utils/unit-tests/package.json
  utils/webpack/lib/convertLanguageToISO.js
  utils/webpack/lib/getAppSettings.js
  utils/webpack/lib/getComponentsSettings.js
  utils/webpack/lib/getDevConfig.js
  utils/webpack/lib/getExtensionsNodeModulesPaths.js
  utils/webpack/lib/getThemeConfig.js
  utils/webpack/lib/getThemeLanguage.js
  utils/webpack/lib/i18n.js
  utils/webpack/lib/logger.js
  utils/webpack/lib/offline.js
  utils/webpack/lib/polyfill.js
  utils/webpack/lib/variables.js
  utils/webpack/locales/en.json
  utils/webpack/package.json
  utils/webpack/plugins/ShopgateIndexerPlugin.js
  utils/webpack/templates/default.ejs
  utils/webpack/webpack.config.js
  yarn.lock
Labels: enhancement

#876 Optimized Hot-Module-Replacement for portal components from extensions.
  libraries/common/components/Portal/index.jsx
  libraries/common/helpers/portals/portalCollection.js
  themes/theme-gmd/index.jsx
  themes/theme-gmd/pages/index.jsx
  themes/theme-ios11/index.jsx
  themes/theme-ios11/pages/index.jsx
  utils/webpack/plugins/ShopgateIndexerPlugin.js
  utils/webpack/webpack.config.js
  yarn.lock
Labels: enhancement

#875 Added JSON schema defintion for the theme configuration.
  themes/theme-gmd/extension-config.schema.json
  themes/theme-ios11/extension-config.schema.json
Labels: enhancement

#880 The frontend process now validates the theme configuration based on the JSON schema.
  utils/webpack/locales/en.json
  utils/webpack/package.json
  utils/webpack/plugins/ShopgateThemeConfigValidatorPlugin.js
  utils/webpack/webpack.config.js
Labels: enhancement

#882 Added new device info selector factories to determine information about supported identity services
  libraries/common/selectors/client.js
  libraries/common/selectors/client.spec.js
Labels: enhancement

#884 Fixed the wrong ordering of fields rendered by the FormBuilder, when no sortIndex is provided.
  libraries/ui-shared/Form/Builder/index.jsx
  libraries/ui-shared/Form/Builder/spec.jsx
Labels: bug
