Repository shopgate/pwa, pull requests merged in 2019-09, with the labels that each got.

#821 Reset selected options of product context, when changing a product on Product details page
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Content/spec.jsx
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Content/spec.jsx
Labels: bug

#822 Fixed circular dependencies
  libraries/common/actions/client/fetchClientInformation.js
  libraries/core/classes/AppCommand/__mocks__/index.spec.js
  libraries/core/classes/AppCommand/index.js
  libraries/core/classes/AppCommand/spec.js
  libraries/core/classes/Bridge/index.js
  libraries/core/classes/Bridge/spec.js
  libraries/core/classes/WebStorageRequest/index.js
  libraries/core/commands/getWebStorageEntry.js
  libraries/core/commands/setWebStorageEntry.js
  libraries/core/helpers/version.js
  libraries/core/helpers/version.spec.js
  libraries/core/index.js
  libraries/engage/components/SheetDrawer/index.jsx
  libraries/engage/components/SheetList/index.jsx
  libraries/engage/core/helpers/__tests__/updateLegacyNavigationBar.spec.js
  libraries/engage/core/helpers/updateLegacyNavigationBar.js
  libraries/tracking/subscriptions/setup.js
Labels: bug

#823 Added the "selectedPaymentInfo" tracking event to the tracking-core
  libraries/tracking-core/core/AppHandler.js
  libraries/tracking-core/helpers/events.js
  libraries/tracking-core/helpers/formatHelpers.js
  libraries/tracking-core/helpers/formatHelpers.spec.js
  libraries/tracking-core/plugins/Base.spec.js
  libraries/tracking-core/tests/BaseTest.js
  libraries/tracking-core/typedef.js
Labels: enhancement

#815 Updated to Babel 7, eslint 5 and jest 24
  .babelrc
  babel.config.js
  extensions/@shopgate-product-reviews/frontend/.babelrc
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-theme-config/frontend/package.json
  extensions/@shopgate-tracking-ga-native/frontend/.babelrc
  extensions/@shopgate-tracking-ga-native/frontend/package.json
  extensions/@shopgate-user-privacy/frontend/package.json
  jest.config.js
  libraries/common/components/Input/index.jsx
  libraries/common/helpers/config/index.js
  libraries/common/package.json
  libraries/core/classes/Conditioner/index.js
  libraries/engage/core/index.js
  libraries/engage/product/components/Media/FeaturedMedia.jsx
  libraries/tracking-core/package.json
  libraries/tracking/package.json
  package.json
  scripts/build-changelog.js
  themes/theme-gmd/.babelrc
  themes/theme-gmd/babel.config.js
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-gmd/components/Search/index.jsx
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/.babelrc
  themes/theme-ios11/babel.config.js
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
  utils/eslint-config/package.json
  utils/eslint-config/ruleset/extras.js
  utils/eslint-config/ruleset/main.js
  utils/eslint-config/ruleset/react.js
  utils/unit-tests/jest.config.js
  utils/unit-tests/package.json
  yarn.lock
Labels: enhancement

#828 A11y: Engage Login Form accessibility adjustments
  libraries/common/components/ModalContainer/index.jsx
  libraries/engage/components/index.js
  libraries/ui-ios/BaseDialog/__snapshots__/spec.jsx.snap
  libraries/ui-ios/BaseDialog/index.jsx
  libraries/ui-material/BaseDialog/__snapshots__/spec.jsx.snap
  libraries/ui-material/BaseDialog/index.jsx
  libraries/ui-shared/ClientInformation/__snapshots__/spec.jsx.snap
  libraries/ui-shared/ClientInformation/index.jsx
  libraries/ui-shared/Dialog/components/PipelineErrorDialog/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Dialog/components/PipelineErrorDialog/index.jsx
  libraries/ui-shared/Sheet/index.jsx
  themes/theme-gmd/pages/Login/components/ForgotPassword/index.jsx
  themes/theme-gmd/pages/Login/index.jsx
  themes/theme-gmd/providers/View/index.jsx
  themes/theme-ios11/pages/Login/components/ForgotPassword/index.jsx
  themes/theme-ios11/pages/Login/index.jsx
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/index.jsx
  themes/theme-ios11/providers/View/index.jsx
Labels: enhancement

#832 Optimised modals for accessibility
  libraries/ui-ios/BaseDialog/__snapshots__/spec.jsx.snap
  libraries/ui-ios/BaseDialog/components/Buttons/__snapshots__/spec.jsx.snap
  libraries/ui-ios/BaseDialog/components/Buttons/index.jsx
  libraries/ui-ios/BaseDialog/components/Buttons/spec.jsx
  libraries/ui-ios/BaseDialog/components/Content/__snapshots__/spec.jsx.snap
  libraries/ui-ios/BaseDialog/components/Content/index.jsx
  libraries/ui-ios/BaseDialog/components/Content/spec.jsx
  libraries/ui-ios/BaseDialog/components/Title/__snapshots__/spec.jsx.snap
  libraries/ui-ios/BaseDialog/components/Title/index.jsx
  libraries/ui-ios/BaseDialog/components/Title/spec.jsx
  libraries/ui-ios/BaseDialog/index.jsx
  libraries/ui-ios/BaseDialog/spec.jsx
  libraries/ui-material/BaseDialog/__snapshots__/spec.jsx.snap
  libraries/ui-material/BaseDialog/components/Buttons/__snapshots__/spec.jsx.snap
  libraries/ui-material/BaseDialog/components/Buttons/index.jsx
  libraries/ui-material/BaseDialog/components/Buttons/spec.jsx
  libraries/ui-material/BaseDialog/components/Content/__snapshots__/spec.jsx.snap
  libraries/ui-material/BaseDialog/components/Content/index.jsx
  libraries/ui-material/BaseDialog/components/Content/spec.jsx
  libraries/ui-material/BaseDialog/components/Title/__snapshots__/spec.jsx.snap
  libraries/ui-material/BaseDialog/components/Title/index.jsx
  libraries/ui-material/BaseDialog/components/Title/spec.jsx
  libraries/ui-material/BaseDialog/index.jsx
  libraries/ui-material/BaseDialog/spec.jsx
  libraries/ui-shared/Dialog/components/PipelineErrorDialog/__snapshots__/spec.jsx.snap
Labels: enhancement

#831 A11y: accessible aria label for back navigation
  libraries/common/helpers/i18n/getTranslator.js
  libraries/common/helpers/i18n/getTranslator.spec.js
  libraries/common/selectors/router.js
  libraries/common/selectors/router.spec.js
  libraries/ui-material/AppBar/components/Icon/index.jsx
  libraries/ui-material/AppBar/components/Title/index.jsx
  themes/theme-gmd/components/AppBar/presets/BackBar/connector.js
  themes/theme-gmd/components/AppBar/presets/BackBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Page/components/Content/index.jsx
  themes/theme-gmd/pages/index.jsx
  themes/theme-gmd/pages/routesTransforms.js
  themes/theme-ios11/components/AppBar/presets/BackBar/connector.js
  themes/theme-ios11/components/AppBar/presets/BackBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Browse/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/Content/spec.jsx
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/index.spec.jsx
  themes/theme-ios11/pages/Page/components/Content/index.jsx
  themes/theme-ios11/pages/index.jsx
  themes/theme-ios11/pages/routesTransforms.js
Labels: enhancement

#833 A11y: accessibility of sort menu for category and search page
  libraries/common/components/Dropdown/index.jsx
  libraries/common/components/SelectBox/__snapshots__/spec.jsx.snap
  libraries/common/components/SelectBox/components/Item/index.jsx
  libraries/common/components/SelectBox/index.jsx
  themes/theme-gmd/components/FilterBar/index.jsx
  themes/theme-gmd/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/FilterBar/index.jsx
  themes/theme-ios11/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
Labels: enhancement

#834 Enabled a11y in Search feature
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/SearchButton/index.jsx
  themes/theme-gmd/components/Search/components/AppBar/index.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Search/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/Search/index.jsx
Labels: enhancement

#835 Fixed spacing between icons and labels of iOS TabBar entries
  themes/theme-ios11/components/TabBar/components/TabBarAction/index.jsx
  themes/theme-ios11/components/TabBar/components/TabBarAction/style.js
Labels: bug

#836 A11y: accessibility for favorites buttons and favorites page
  libraries/common/components/Link/__snapshots__/spec.jsx.snap
  libraries/common/components/Link/index.jsx
  libraries/common/helpers/config/mock.js
  libraries/ui-material/SnackBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartButton/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemFavoritesButton/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemFavoritesButton/style.js
  themes/theme-gmd/components/ProductGrid/components/Item/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/style.js
  themes/theme-gmd/components/Reviews/components/Header/__snapshots__/spec.jsx.snap
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/Image/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/style.js
  themes/theme-gmd/pages/Favorites/index.jsx
  themes/theme-gmd/pages/Favorites/subscriptions.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemFavoritesButton/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemFavoritesButton/style.js
  themes/theme-ios11/components/ProductGrid/components/Item/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/style.js
  themes/theme-ios11/components/Reviews/components/Header/__snapshots__/spec.jsx.snap
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Browse/components/RootCategories/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/Image/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/style.js
  themes/theme-ios11/pages/Favorites/index.jsx
  themes/theme-ios11/pages/Favorites/subscriptions.js
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: enhancement

#838 Implemented the process type `PROCESS_LAST` in the `PipelineManager` and changed the `fetchCart` action accordingly. `fetchCart` now returns a promise.
  libraries/commerce/cart/actions/fetchCart.js
  libraries/core/classes/PipelineManager/index.js
  libraries/core/classes/PipelineManager/spec.js
Labels: enhancement

#839 Remove recompose library in favor of React 16.6 memo
  libraries/commerce/package.json
  libraries/common/package.json
  themes/theme-gmd/babel.config.js
  themes/theme-gmd/components/NavDrawer/components/LogoutButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/Main/components/CartButton/components/Badge/index.jsx
  themes/theme-gmd/components/NavDrawer/components/Main/components/FavoritesButton/components/Badge/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/index.jsx
  themes/theme-gmd/components/Viewport/index.jsx
  themes/theme-gmd/deps/recompose/index.js
  themes/theme-gmd/deps/recompose/package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Manufacturer/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Name/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/PriceInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Rating/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Rating/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Shipping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Shipping/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/TaxDisclaimer/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/components/Tier/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/components/Tier/spec.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/spec.jsx
  themes/theme-ios11/babel.config.js
  themes/theme-ios11/components/ProductGrid/components/Item/index.jsx
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/deps/recompose/index.js
  themes/theme-ios11/deps/recompose/package.json
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/Product/components/Header/components/Availability/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Manufacturer/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Name/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/PriceInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Rating/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Rating/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Shipping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Shipping/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/TaxDisclaimer/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/components/Tier/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/components/Tier/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/spec.jsx
  yarn.lock
Labels: polish
