Repository shopgate/pwa, pull requests merged in 2019-07, with the labels that each got.

#718 Fixed an issue with changelog compare links
  Makefile
  scripts/build-changelog.js
Labels: polish

#717 Added support for Universal Links
  libraries/common/action-creators/app/index.js
  libraries/common/action-creators/app/spec.js
  libraries/common/actions/app/handleLink.js
  libraries/common/actions/app/handleLink.spec.js
  libraries/common/actions/app/handleUniversalLink.js
  libraries/common/actions/app/registerLinkEvents.js
  libraries/common/constants/ActionTypes.js
  libraries/engage/core/index.js
  libraries/tracking/subscriptions/deeplinkPush.js
Labels: enhancement

#720 Media embed code shows incorrect preview
  libraries/common/collections/media-providers/MediaProvider.js
  libraries/common/collections/media-providers/MediaProvider.spec.js
  libraries/common/collections/media-providers/__snapshots__/MediaProvider.spec.js.snap
  libraries/common/collections/media-providers/style.js
  libraries/common/helpers/dom/index.js
Labels: bug

#719 Handle external media provider scripts without blocking app start
  extensions/@shopgate-theme-config/frontend/package.json
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/MediaProvider.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/collections/media-providers/YouTube.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/__snapshots__/spec.jsx.snap
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/components/HtmlSanitizer/spec.jsx
  libraries/common/package.json
  themes/theme-gmd/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Html/__snapshots__/spec.jsx.snap
Labels: bug

#724 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/MediaProvider.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/collections/media-providers/YouTube.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/__snapshots__/spec.jsx.snap
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/components/HtmlSanitizer/spec.jsx
  libraries/common/package.json
  themes/theme-gmd/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Html/__snapshots__/spec.jsx.snap
Labels: bug

#727 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
Labels: bug

#728 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
Labels: bug

#729 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
Labels: bug

#730 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
Labels: bug

#731 Handle external media provider scripts without blocking app start
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/package.json
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/index.jsx
Labels: bug

#723 Handle external media provider scripts without blocking app start
  extensions/@shopgate-theme-config/frontend/package.json
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/media-providers/MediaProvider.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/collections/media-providers/YouTube.js
  libraries/common/components/EmbeddedMedia/index.jsx
  libraries/common/components/EmbeddedMedia/spec.jsx
  libraries/common/components/HtmlSanitizer/__snapshots__/spec.jsx.snap
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/components/HtmlSanitizer/spec.jsx
  libraries/common/package.json
  themes/theme-gmd/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Html/__snapshots__/spec.jsx.snap
Labels: bug

#740 Onload command is independent of clientInformation
  libraries/core/commands/onload.js
Labels: bug

#741 Onload command is independent of clientInformation
  libraries/core/commands/onload.js
Labels: bug

#742 Onload command is independent of clientInformation
  libraries/core/commands/onload.js
Labels: bug

#743 Start page renders immediately when React is ready.
  themes/theme-gmd/pages/StartPage/index.jsx
  themes/theme-ios11/pages/StartPage/index.jsx
Labels: bug

#744 Start page renders immediately when React is ready.
  themes/theme-gmd/pages/StartPage/index.jsx
  themes/theme-ios11/pages/StartPage/index.jsx
Labels: bug

#745 Start page renders immediately when React is ready.
  themes/theme-gmd/pages/StartPage/index.jsx
  themes/theme-ios11/pages/StartPage/index.jsx
Labels: bug

#748 Fix displaying unit price on product details page for product without variants
  themes/theme-gmd/pages/Product/components/Header/components/Price/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Price/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Price/spec.jsx
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/components/Tier/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/components/Tier/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/components/Tier/spec.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Price/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Price/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Price/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/components/Tier/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/components/Tier/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/components/Tier/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/spec.jsx
Labels: bug

#750 Fixed an issue with the Ellipsis component
  libraries/common/package.json
Labels: bug

#749 Fixed an issue with the Ellipsis component
  libraries/common/package.json
Labels: bug

#752 Fixed an issue with the Ellipsis component
  libraries/common/package.json
Labels: bug

#754 Fixed an issue with the Ellipsis component
  libraries/common/package.json
Labels: bug

#753 Fixed an issue with the Ellipsis component
  libraries/common/package.json
Labels: bug

#755 Fixed an issue with the Ellipsis component
  libraries/common/components/Ellipsis/index.jsx
  libraries/common/package.json
  yarn.lock
Labels: bug

#759 Improved product characteristics auto selection
  libraries/common/components/ProductCharacteristics/helpers/index.js
  libraries/common/components/ProductCharacteristics/helpers/index.spec.js
  libraries/common/components/ProductCharacteristics/index.jsx
Labels: enhancement

#722 Added functionality to access widget and page configs and settings outside of the react scope.
  libraries/engage/core/config/__tests__/getPageConfig.spec.js
  libraries/engage/core/config/__tests__/getPageSettings.spec.js
  libraries/engage/core/config/__tests__/getThemeAssets.spec.js
  libraries/engage/core/config/__tests__/getThemeColors.spec.js
  libraries/engage/core/config/__tests__/getThemeConfig.spec.js
  libraries/engage/core/config/__tests__/getThemeSettings.spec.js
  libraries/engage/core/config/__tests__/getWidgetConfig.spec.js
  libraries/engage/core/config/__tests__/getWidgetSettings.spec.js
  libraries/engage/core/config/getPageConfig.js
  libraries/engage/core/config/getPageSettings.js
  libraries/engage/core/config/getThemeAssets.js
  libraries/engage/core/config/getThemeColors.js
  libraries/engage/core/config/getThemeConfig.js
  libraries/engage/core/config/getThemeSettings.js
  libraries/engage/core/config/getWidgetConfig.js
  libraries/engage/core/config/getWidgetSettings.js
  libraries/engage/core/hooks/__tests__/usePageConfig.spec.js
  libraries/engage/core/hooks/__tests__/usePageSettings.spec.js
  libraries/engage/core/hooks/__tests__/useWidgetConfig.spec.js
  libraries/engage/core/hooks/__tests__/useWidgetSettings.spec.js
  libraries/engage/core/hooks/__tests__/useWidgetStyles.spec.js
  libraries/engage/core/hooks/usePageConfig.js
  libraries/engage/core/hooks/usePageSettings.js
  libraries/engage/core/hooks/useWidgetConfig.js
  libraries/engage/core/hooks/useWidgetSettings.js
  libraries/engage/core/hooks/useWidgetStyles.js
  libraries/engage/core/index.js
  libraries/engage/product/components/Swatch/Swatch.jsx
  libraries/engage/product/components/Swatches/Swatches.jsx
Labels: enhancement

#758 Adjust slider navigation on product details page
  libraries/common/components/Swiper/index.jsx
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#725 Added a sheet to show all Related Products on the PDP
  extensions/@shopgate-theme-config/extension/mockedRelations.json
  extensions/@shopgate-theme-config/frontend/config-common.js
  libraries/commerce/product/reducers/productsById.js
  libraries/commerce/product/selectors/relations.js
  libraries/engage/product/components/RelationsSlider/RelationsSheet.connector.js
  libraries/engage/product/components/RelationsSlider/RelationsSheet.jsx
  libraries/engage/product/components/RelationsSlider/RelationsSlider.connector.js
  libraries/engage/product/components/RelationsSlider/RelationsSlider.jsx
  libraries/engage/product/components/RelationsSlider/RelationsSliderContent.jsx
  libraries/engage/product/components/RelationsSlider/connector.js
  libraries/engage/product/components/RelationsSlider/index.js
  libraries/engage/product/components/RelationsSlider/style.js
  libraries/engage/product/index.js
  libraries/engage/product/selectors/__tests__/price.spec.js
  libraries/engage/product/selectors/__tests__/product.spec.js
  libraries/engage/product/selectors/__tests__/relations.spec.js
  libraries/engage/product/selectors/helpers/index.js
  libraries/engage/product/selectors/helpers/wrapMemoizedSelector.js
  libraries/engage/product/selectors/relations.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#747 Translation files are incomplete and partially wrong
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: bug

#763 Re-position toast component
  libraries/ui-material/SnackBar/index.jsx
  libraries/ui-material/SnackBar/style.js
  libraries/ui-shared/Footer/index.jsx
  libraries/ui-shared/Footer/index.spec.jsx
  libraries/ui-shared/Footer/style.js
  libraries/ui-shared/Sheet/index.jsx
  libraries/ui-shared/Sheet/spec.jsx
  themes/theme-gmd/components/SnackBar/index.jsx
  themes/theme-ios11/components/SnackBar/index.jsx
Labels: bug

#764 Added missing translations strings for a11y
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#760 The product image updates when a characteristic is selected.
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/engage/product/components/ProductImage/index.jsx
  libraries/engage/product/index.js
  libraries/engage/product/selectors/__tests__/variants.spec.js
  libraries/engage/product/selectors/variants.js
  themes/theme-gmd/pages/Product/components/Characteristics/index.jsx
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Media/connector.js
  themes/theme-gmd/pages/Product/components/Media/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/index.jsx
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Media/connector.js
  themes/theme-ios11/pages/Product/components/Media/index.jsx
Labels: enhancement

#761 Add default fetch products parameters, fetch favorite products data
  libraries/commerce/favorites/streams/index.js
  libraries/commerce/favorites/subscriptions/index.js
  libraries/commerce/favorites/subscriptions/spec.js
  libraries/commerce/product/actions/fetchProduct.js
  libraries/commerce/product/actions/fetchProducts.js
  libraries/commerce/product/actions/fetchProductsById.js
  libraries/commerce/product/reducers/productsById.js
  libraries/commerce/product/reducers/resultsByHash.js
  libraries/common/constants/Configuration.js
  libraries/engage/product/components/ProductImage/__snapshots__/spec.jsx.snap
  libraries/engage/product/helpers/index.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/index.jsx
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/index.jsx
  themes/theme-ios11/pages/subscriptions.js
Labels: bug

#770 Updated ProductSlider theme component to use Slider.Item wrapper for given ProductCard
  themes/theme-gmd/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductSlider/index.jsx
  themes/theme-gmd/components/ProductSlider/spec.jsx
  themes/theme-ios11/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductSlider/spec.jsx
Labels: bug

#769 Added empty data check to getKnownRelatives selector
  libraries/commerce/product/selectors/variants.js
  libraries/commerce/product/selectors/variants.spec.js
Labels: bug

#772 Fixed an issue where the Swiper component didn't update as expected
  libraries/common/components/Swiper/index.jsx
  libraries/common/package.json
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  yarn.lock
Labels: bug

#774 Enhance Swiper Component
  libraries/common/components/Swiper/index.jsx
  themes/theme-gmd/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductSlider/index.jsx
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductSlider/index.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/index.jsx
Labels: bug, enhancement

#775 Prevented opening of the product gallery from placeholder images
  jest.config.js
  themes/theme-gmd/pages/Product/components/Media/components/ImageSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/components/ImageSlider/index.jsx
Labels: bug

#771 Added padding to Swiper component in Engage library to show a shadow for product cards
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#776 Adding a product+coupon via qr-code redirects to cart
  libraries/commerce/cart/streams/index.js
  libraries/commerce/cart/streams/index.spec.js
  libraries/commerce/cart/subscriptions/index.js
  libraries/commerce/cart/subscriptions/index.spec.js
Labels: bug

#756 Show placeholder or featured media on product details page
  Makefile
  extensions/@shopgate-theme-config/frontend/config-gmd.js
  extensions/@shopgate-theme-config/frontend/config-ios.js
  libraries/commerce/product/constants/index.js
  libraries/commerce/product/index.js
  libraries/commerce/product/selectors/media.js
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/selectors/product.spec.js
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/engage/product/components/Media/FeaturedImage.jsx
  libraries/engage/product/components/Media/FeaturedMedia.jsx
  libraries/engage/product/components/Media/MediaImage.jsx
  libraries/engage/product/components/Media/MediaPlaceholder.jsx
  libraries/engage/product/components/Media/style.js
  libraries/engage/product/components/MediaSlider/components/MediaImage/index.jsx
  libraries/engage/product/components/MediaSlider/connector.js
  libraries/engage/product/components/MediaSlider/index.jsx
  libraries/engage/product/constants/index.js
  libraries/engage/product/index.js
  libraries/engage/product/selectors/__tests__/media.spec.js
  libraries/engage/product/selectors/__tests__/product.spec.js
  libraries/engage/product/selectors/__tests__/variants.spec.js
  libraries/engage/product/selectors/media.js
  libraries/engage/product/selectors/product.js
  libraries/engage/product/selectors/variants.js
  themes/theme-gmd/pages/Product/components/Characteristics/index.jsx
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/connector.js
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-gmd/pages/Product/components/Media/components/ProductMediaSlider/connector.js
  themes/theme-gmd/pages/Product/components/Media/components/ProductMediaSlider/index.jsx
  themes/theme-gmd/pages/Product/components/Media/connector.js
  themes/theme-gmd/pages/Product/components/Media/index.jsx
  themes/theme-gmd/pages/ProductGallery/components/Content/components/MediaSlider/connector.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/index.jsx
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/connector.js
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/components/ProductMediaSlider/connector.js
  themes/theme-ios11/pages/Product/components/Media/components/ProductMediaSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/connector.js
  themes/theme-ios11/pages/Product/components/Media/index.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/components/MediaSlider/connector.js
  themes/theme-ios11/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
Labels: bug

#778 Fix video autoplay on cms pages
  libraries/common/collections/EmbeddedMedia.js
  libraries/common/collections/EmbeddedMedia.spec.js
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/history.js
Labels: bug

#777 Long product names are hyphened and cur off correctly in ProductGrid
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemName/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemName/index.jsx
  themes/theme-gmd/pages/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemName/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemName/index.jsx
  themes/theme-ios11/pages/index.jsx
Labels: bug

#757 Refactored favorites actions to use add and delete favorites pipelines instead of put
  libraries/commerce/favorites/action-creators/index.js
  libraries/commerce/favorites/actions/addFavorites.js
  libraries/commerce/favorites/actions/addFavorites.spec.js
  libraries/commerce/favorites/actions/fetchFavorites.spec.js
  libraries/commerce/favorites/actions/removeFavorites.js
  libraries/commerce/favorites/actions/removeFavorites.spec.js
  libraries/commerce/favorites/actions/spec.js
  libraries/commerce/favorites/actions/toggleFavorites.js
  libraries/commerce/favorites/actions/toggleFavorites.spec.js
  libraries/commerce/favorites/constants/Pipelines.js
  libraries/commerce/favorites/constants/index.js
  libraries/commerce/favorites/index.js
  libraries/commerce/favorites/reducers/products.js
  libraries/commerce/favorites/reducers/spec.js
  libraries/commerce/favorites/streams/index.js
  libraries/commerce/favorites/streams/spec.js
  libraries/commerce/favorites/subscriptions/index.js
  libraries/commerce/favorites/subscriptions/spec.js
  libraries/common/subscriptions/mock.js
  libraries/engage/favorites/index.js
  libraries/ui-shared/FavoritesButton/index.jsx
  libraries/ui-shared/FavoritesButton/spec.jsx
  themes/theme-gmd/pages/Favorites/subscriptions.js
  themes/theme-ios11/pages/Favorites/subscriptions.js
Labels: enhancement

#780 Grouped properties labels are translated.
  libraries/commerce/product/subscriptions/index.js
  libraries/engage/product/components/EffectivityDates/helpers.js
  libraries/engage/product/components/ProductProperties/GroupedProperties.jsx
  libraries/engage/product/helpers/redirects.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#779 Fixed Padding to only apply to ProductSlider component from ThemeApi
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductSlider/index.jsx
  themes/theme-gmd/components/ProductSlider/style.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ProductSlider/style.js
  themes/theme-ios11/components/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductSlider/style.js
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ProductSlider/style.js
  yarn.lock
Labels: bug

#781 Added the locations & availability configuration.
  extensions/@shopgate-theme-config/frontend/config-common.js
Labels: enhancement

#782 Added functionality to determine geolocation coordinates
  libraries/commerce/scanner/actions/grantCameraPermissions.js
  libraries/commerce/scanner/index.js
  libraries/engage/core/actions/__tests__/getGeolocation.spec.js
  libraries/engage/core/actions/__tests__/grantCameraPermissions.spec.js
  libraries/engage/core/actions/__tests__/grantGeolocationPermissions.spec.js
  libraries/engage/core/actions/__tests__/grantPermissions.spec.js
  libraries/engage/core/actions/getGeolocation.js
  libraries/engage/core/actions/grantCameraPermissions.js
  libraries/engage/core/actions/grantGeolocationPermissions.js
  libraries/engage/core/actions/grantPermissions.js
  libraries/engage/core/classes/GeolocationRequest.js
  libraries/engage/core/classes/__tests__/GeolocationRequest.spec.js
  libraries/engage/core/constants/geolocationRequest.js
  libraries/engage/core/index.js
  libraries/engage/scanner/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-gmd/pages/subscriptions.spec.js
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/subscriptions.js
  themes/theme-ios11/pages/subscriptions.spec.js
Labels: enhancement
