Repository shopgate/pwa, pull requests merged in 2019-06, with the labels that each got.

#681 Handle not found product on Product Detail Page
  libraries/commerce/product/streams/index.js
  libraries/commerce/product/streams/index.spec.js
  libraries/commerce/product/subscriptions/index.js
  libraries/commerce/product/subscriptions/index.spec.js
  libraries/common/streams/main.js
Labels: bug

#682 Support empty defaults for elements of type select in Form Builder with required flag
  libraries/ui-shared/Form/Builder/builders/buildFormDefaults.js
  libraries/ui-shared/Form/Builder/builders/buildFormDefaults.spec.js
Labels: bug

#684 Support Swatches on Product Details Page
  extensions/@shopgate-theme-config/extension-config.json
  extensions/@shopgate-theme-config/extension/mockEffectiveDates.js
  extensions/@shopgate-theme-config/extension/mockSwatchesVariants.js
  extensions/@shopgate-theme-config/frontend/config-common.js
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/common/helpers/config/index.js
  libraries/common/helpers/data/index.js
  libraries/engage/core/config/ThemeConfigResolver.js
  libraries/engage/product/components/Swatch/Swatch.jsx
  libraries/engage/product/components/Swatch/SwatchColor.jsx
  libraries/engage/product/components/Swatch/SwatchTexture.jsx
  libraries/engage/product/components/Swatch/style.js
  libraries/engage/product/components/Swatches/Swatches.jsx
  libraries/engage/product/components/Swatches/style.js
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/index.jsx
  themes/theme-gmd/pages/Product/components/Characteristics/Swatch/index.jsx
  themes/theme-gmd/pages/Product/components/Characteristics/Swatch/style.js
  themes/theme-gmd/pages/Product/components/Characteristics/index.jsx
  themes/theme-gmd/pages/Product/components/Characteristics/transition.js
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Swatch/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Swatch/style.js
  themes/theme-ios11/pages/Product/components/Characteristics/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/transition.js
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/index.jsx
Labels: enhancement

#683 Added accessibility tree to the TabBar in iOS.
  libraries/common/components/Button/index.jsx
  libraries/ui-ios/AppBar/index.jsx
  themes/theme-ios11/components/TabBar/components/FavoritesAction/style.js
  themes/theme-ios11/components/TabBar/components/MoreAction/style.js
  themes/theme-ios11/components/TabBar/components/TabBarAction/index.jsx
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/components/TabBar/tabs.js
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/pages/Browse/index.jsx
  themes/theme-ios11/pages/Category/index.jsx
  themes/theme-ios11/pages/Product/index.jsx
Labels: enhancement

#688 Fixed secure config writer to correctly merge arrays
  extensions/@shopgate-theme-config/extension-config.json
  extensions/@shopgate-theme-config/extension/mockEffectiveDates.js
  extensions/@shopgate-theme-config/extension/mockMapPrice.js
  extensions/@shopgate-theme-config/extension/mockMinMaxOrder.js
  extensions/@shopgate-theme-config/extension/mockNotFoundProduct.js
  extensions/@shopgate-theme-config/extension/mockProductMedia.js
  extensions/@shopgate-theme-config/extension/mockSwatches.js
  extensions/@shopgate-theme-config/extension/mockSwatchesVariants.js
  extensions/@shopgate-theme-config/frontend/index.js
  extensions/@shopgate-theme-config/frontend/package.json
  libraries/common/helpers/config/index.js
  libraries/common/helpers/config/theme.js
  libraries/common/helpers/data/index.js
  libraries/common/helpers/data/spec.js
Labels: bug

#690 Fixed an issue with missing dependencies for the react-player module.
  libraries/engage/package.json
  yarn.lock
Labels: bug

#691 Prevent getProductMedia pipeline from being called in none beta environment.
  libraries/commerce/product/actions/fetchProductMedia.js
  libraries/commerce/product/subscriptions/index.js
Labels: bug

#693 Support effectivity dates on Product List Page
  extensions/@shopgate-theme-config/extension-config.json
  extensions/@shopgate-theme-config/extension/mockCatalog2Data.js
  extensions/@shopgate-theme-config/extension/mockEffectiveDates.js
  extensions/@shopgate-theme-config/extension/mockMapPrice.js
  extensions/@shopgate-theme-config/extension/mockMinMaxOrder.js
  extensions/@shopgate-theme-config/extension/mockNotFoundProduct.js
  extensions/@shopgate-theme-config/frontend/config-common.js
  libraries/commerce/category/actions/fetchCategoryProducts.js
  libraries/commerce/product/action-creators/expireProductById.js
  libraries/commerce/product/actions/fetchProducts.js
  libraries/commerce/product/helpers/index.js
  libraries/commerce/product/reducers/resultsByHash.js
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/subscriptions/index.js
  libraries/commerce/product/subscriptions/index.spec.js
  libraries/commerce/search/actions/fetchSearchResults.js
  libraries/common/helpers/date/index.js
  libraries/common/helpers/date/spec.js
  libraries/common/streams/main.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
  libraries/engage/core/config/getThemeConfig.js
  libraries/engage/core/config/getThemeSettings.js
  libraries/engage/core/hooks/__tests__/useConfig.spec.js
  libraries/engage/core/hooks/__tests__/useSettings.spec.js
  libraries/engage/core/hooks/useConfig.js
  libraries/engage/core/hooks/useSettings.js
  libraries/engage/core/index.js
  libraries/engage/product/components/EffectivityDates/constants.js
  libraries/engage/product/components/EffectivityDates/helpers.js
  libraries/engage/product/components/EffectivityDates/index.jsx
  libraries/engage/product/components/EffectivityDates/style.js
  libraries/engage/product/helpers/index.js
  libraries/engage/product/helpers/redirects.js
  libraries/engage/product/index.js
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemDetails/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemDetails/index.jsx
  themes/theme-gmd/pages/Category/components/Products/actions/getProducts.js
  themes/theme-gmd/pages/Category/components/Products/connector.js
  themes/theme-gmd/pages/Category/subscriptions.js
  themes/theme-gmd/pages/Search/components/Products/actions/getProducts.js
  themes/theme-gmd/pages/Search/components/Products/connector.js
  themes/theme-gmd/pages/Search/subscriptions.js
  themes/theme-gmd/pages/Search/subscriptions.spec.js
  themes/theme-gmd/pages/index.jsx
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/index.jsx
  themes/theme-ios11/pages/Category/components/Products/actions/getProducts.js
  themes/theme-ios11/pages/Category/components/Products/connector.js
  themes/theme-ios11/pages/Category/subscriptions.js
  themes/theme-ios11/pages/Search/components/Products/actions/getProducts.js
  themes/theme-ios11/pages/Search/components/Products/connector.js
  themes/theme-ios11/pages/Search/subscriptions.js
  themes/theme-ios11/pages/Search/subscriptions.spec.js
  themes/theme-ios11/pages/index.jsx
  themes/theme-ios11/pages/subscriptions.js
Labels: enhancement

#695 Configuration added to configure zoom ratio for product gallery
  extensions/@shopgate-theme-config/frontend/config-common.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/index.jsx
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/spec.jsx
  themes/theme-gmd/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
  themes/theme-gmd/pages/ProductGallery/constants.js
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/index.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/spec.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/index.jsx
  themes/theme-ios11/pages/ProductGallery/constants.js
Labels: enhancement

#696 Fixed incorrect price display on the product detail page when options are involved.
  libraries/commerce/product/selectors/options.js
  libraries/commerce/product/selectors/price.spec.js
  themes/theme-gmd/pages/Product/components/Options/components/Option/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/Option/index.jsx
Labels: bug

#698 Make modal window title translatable with parameters
  libraries/ui-ios/BaseDialog/index.jsx
  libraries/ui-ios/BaseDialog/spec.jsx
  libraries/ui-material/BaseDialog/index.jsx
  libraries/ui-material/BaseDialog/spec.jsx
  libraries/ui-shared/Dialog/components/TextMessageDialog/index.jsx
  libraries/ui-shared/Dialog/components/TextMessageDialog/spec.jsx
  libraries/ui-shared/Dialog/components/VariantSelectModal/index.jsx
  libraries/ui-shared/Dialog/index.jsx
  libraries/ui-shared/Dialog/spec.jsx
Labels: enhancement

#703 Polished the `Swatch` components to make them show up properly in the React DOM.
  libraries/engage/product/components/Swatch/Swatch.jsx
  libraries/engage/product/components/Swatch/SwatchColor.jsx
  libraries/engage/product/components/Swatch/SwatchTexture.jsx
Labels: polish

#699 A PDP can now show related products in a slider
  extensions/@shopgate-theme-config/extension-config.json
  extensions/@shopgate-theme-config/extension/mockProductRelations.js
  extensions/@shopgate-theme-config/extension/mockedRelations.json
  extensions/@shopgate-theme-config/frontend/config-common.js
  libraries/commerce/product/reducers/productRelationsByHash.js
  libraries/common/components/index.js
  libraries/engage/package.json
  libraries/engage/product/components/ProductCard/index.jsx
  libraries/engage/product/components/ProductCard/style.js
  libraries/engage/product/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  libraries/engage/product/components/ProductGridPrice/index.jsx
  libraries/engage/product/components/ProductGridPrice/index.spec.jsx
  libraries/engage/product/components/ProductGridPrice/style.js
  libraries/engage/product/components/RelationsSlider/RelationsSlider.jsx
  libraries/engage/product/components/RelationsSlider/RelationsSliderContent.jsx
  libraries/engage/product/components/RelationsSlider/connector.js
  libraries/engage/product/components/RelationsSlider/constants.js
  libraries/engage/product/components/RelationsSlider/index.js
  libraries/engage/product/components/RelationsSlider/style.js
  libraries/engage/product/index.js
  libraries/ui-shared/Card/style.js
  libraries/ui-shared/index.js
  themes/theme-gmd/components/ProductCard/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemPrice/index.jsx
  themes/theme-gmd/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/ProductGridPrice/style.js
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/index.spec.jsx
  themes/theme-gmd/widgets/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/components/ProductCard/style.js
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemPrice/index.jsx
  themes/theme-ios11/components/ProductGridPrice/index.jsx
  themes/theme-ios11/components/ProductGridPrice/index.spec.jsx
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/index.spec.jsx
  themes/theme-ios11/widgets/ProductSlider/index.jsx
Labels: enhancement

#701 Added functionality to access theme config entries in an easy fashion
  libraries/engage/core/config/__tests__/getThemeAssets.spec.js
  libraries/engage/core/config/__tests__/getThemeColors.spec.js
  libraries/engage/core/config/__tests__/getThemeSettings.spec.js
  libraries/engage/core/config/getThemeAssets.js
  libraries/engage/core/config/getThemeColors.js
  libraries/engage/core/config/getThemeConfig.js
  libraries/engage/core/config/getThemeSettings.js
  libraries/engage/core/hooks/__tests__/useAssets.spec.js
  libraries/engage/core/hooks/__tests__/useColors.spec.js
  libraries/engage/core/hooks/__tests__/useConfig.spec.js
  libraries/engage/core/hooks/__tests__/useIcons.spec.js
  libraries/engage/core/hooks/__tests__/usePageConfig.spec.js
  libraries/engage/core/hooks/__tests__/useSettings.spec.js
  libraries/engage/core/hooks/__tests__/useWidgetConfig.spec.js
  libraries/engage/core/hooks/useAssets.js
  libraries/engage/core/hooks/useColors.js
  libraries/engage/core/hooks/useIcons.js
  libraries/engage/core/hooks/usePageConfig.js
  libraries/engage/core/hooks/useSettings.js
  libraries/engage/core/hooks/useWidgetConfig.js
  libraries/engage/core/index.js
Labels: enhancement

#704 Support featured media for product list and product details page
  extensions/@shopgate-theme-config/extension-config.json
  extensions/@shopgate-theme-config/extension/mockProductMedia.js
  extensions/@shopgate-theme-config/frontend/config-gmd.js
  extensions/@shopgate-theme-config/frontend/config-ios.js
  extensions/@shopgate-theme-config/pipelines/shopgate.catalog.getProductMedia.v1.json
  libraries/common/constants/Configuration.js
  libraries/common/subscriptions/app.js
  libraries/engage/components/NullComponent/index.jsx
  libraries/engage/components/constants.js
  libraries/engage/components/index.js
  libraries/engage/product/components/Media/FeaturedImage.jsx
  libraries/engage/product/components/Media/FeaturedMedia.jsx
  libraries/engage/product/components/Media/FeaturedVideo.jsx
  libraries/engage/product/components/Media/MediaImage.jsx
  libraries/engage/product/components/Media/helpers.js
  libraries/engage/product/components/Media/helpers.spec.js
  libraries/engage/product/components/Media/index.js
  libraries/engage/product/components/Media/props.js
  libraries/engage/product/components/Media/style.js
  libraries/engage/product/components/MediaSlider/components/MediaImage/index.jsx
  libraries/engage/product/components/MediaSlider/components/MediaVideo/index.jsx
  libraries/engage/product/components/MediaSlider/index.jsx
  libraries/engage/product/components/MediaSlider/style.js
  libraries/engage/product/index.js
  themes/theme-gmd/components/ProductCard/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/index.jsx
  themes/theme-gmd/pages/Product/components/Media/connector.js
  themes/theme-gmd/pages/Product/components/Media/index.jsx
  themes/theme-gmd/pages/ProductGallery/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
  themes/theme-gmd/pages/ProductGallery/components/Content/connector.js
  themes/theme-gmd/pages/ProductGallery/components/Content/index.jsx
  themes/theme-gmd/themeApi/ProductCard/components/Render/index.jsx
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/index.jsx
  themes/theme-ios11/pages/Product/components/Media/connector.js
  themes/theme-ios11/pages/Product/components/Media/index.jsx
  themes/theme-ios11/pages/ProductGallery/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/MediaSlider/index.jsx
  themes/theme-ios11/pages/ProductGallery/components/Content/connector.js
  themes/theme-ios11/pages/ProductGallery/components/Content/index.jsx
  themes/theme-ios11/themeApi/ProductCard/components/Render/index.jsx
Labels: enhancement

#708 Portuguese pt-PT locale for user privacy labels
  extensions/@shopgate-user-privacy/extension-config.json
Labels: bug

#700 Introduced a global translation helper
  libraries/common/App.jsx
  libraries/common/components/I18n/components/FormatDate/__snapshots__/spec.jsx.snap
  libraries/common/components/I18n/components/FormatDate/index.jsx
  libraries/common/components/I18n/components/FormatDate/spec.jsx
  libraries/common/components/I18n/components/FormatNumber/__snapshots__/spec.jsx.snap
  libraries/common/components/I18n/components/FormatNumber/index.jsx
  libraries/common/components/I18n/components/FormatNumber/spec.jsx
  libraries/common/components/I18n/components/FormatPrice/__snapshots__/spec.jsx.snap
  libraries/common/components/I18n/components/FormatPrice/index.jsx
  libraries/common/components/I18n/components/FormatPrice/spec.jsx
  libraries/common/components/I18n/components/FormatTime/index.jsx
  libraries/common/components/I18n/components/FormatTime/spec.jsx
  libraries/common/components/I18n/components/I18nProvider/index.jsx
  libraries/common/components/I18n/components/I18nProvider/spec.jsx
  libraries/common/components/I18n/components/Placeholder/__snapshots__/spec.jsx.snap
  libraries/common/components/I18n/components/Placeholder/spec.jsx
  libraries/common/components/I18n/components/Translate/__snapshots__/spec.jsx.snap
  libraries/common/components/I18n/components/Translate/index.jsx
  libraries/common/components/I18n/components/Translate/spec.jsx
  libraries/engage/core/helpers/__mocks__/i18n.js
  libraries/engage/core/helpers/i18n.js
  libraries/engage/core/helpers/i18n.spec.js
  libraries/engage/core/index.js
  libraries/engage/product/components/ProductGridPrice/index.spec.jsx
  themes/theme-gmd/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/spec.jsx
  themes/theme-gmd/pages/index.jsx
  themes/theme-ios11/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/spec.jsx
  themes/theme-ios11/pages/index.jsx
  utils/unit-tests/testSetup.js
Labels: enhancement

#709 Improved safe area insets
  themes/theme-gmd/components/Viewport/style.js
  themes/theme-ios11/components/Viewport/style.js
Labels: enhancement

#706 SheetList item correct styling
  libraries/engage/components/SheetList/__snapshots__/spec.jsx.snap
  libraries/engage/components/SheetList/components/Item/__snapshots__/spec.jsx.snap
  libraries/engage/components/SheetList/components/Item/index.jsx
  libraries/engage/components/SheetList/components/Item/style.js
  libraries/engage/components/SheetList/index.jsx
  libraries/engage/components/SheetList/style.js
  libraries/engage/product/components/PriceDifference/index.jsx
  libraries/engage/product/components/PriceDifference/style.js
  libraries/engage/product/index.js
  libraries/ui-shared/Glow/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Glow/index.jsx
  themes/theme-gmd/components/Picker/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/Picker/style.js
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/SheetItem/style.js
  themes/theme-gmd/pages/Product/components/Options/components/Option/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/Option/style.js
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/style.js
  themes/theme-gmd/pages/Product/components/Options/index.jsx
  themes/theme-gmd/themeApi/index.js
  themes/theme-gmd/widgets/CategoryList/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/NestedCategoryFilter/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/widgets/NestedCategoryFilter/components/Picker/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/widgets/NestedCategoryFilter/components/Picker/components/SheetItem/style.js
  themes/theme-ios11/components/Picker/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/Picker/style.js
  themes/theme-ios11/pages/Browse/components/RootCategories/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Options/components/Option/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/PriceDifference/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/PriceDifference/style.js
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/style.js
  themes/theme-ios11/pages/Product/components/Options/index.jsx
  themes/theme-ios11/themeApi/index.js
  themes/theme-ios11/widgets/CategoryList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/NestedCategoryFilter/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/widgets/NestedCategoryFilter/components/Picker/__snapshots__/index.spec.jsx.snap
Labels: bug

#713 Changed shopify-webcheckout url logic to accept a full domain over the alias for the web-login.
  CHANGELOG.md
  libraries/webcheckout/selectors/index.js
  themes/theme-gmd/CHANGELOG.md
  themes/theme-ios11/CHANGELOG.md
Labels: bug

#714 Applied react-hot-loader patch to the themes
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
Labels: bug
