Repository shopgate/pwa, pull requests merged in 2019-04, with the labels that each got.

#590 Patch for e2e tests for new slider implementation
  themes/theme-gmd/e2e/elements/de.js
  themes/theme-gmd/e2e/helper/navigation.js
  themes/theme-gmd/e2e/integration/consistency/StartPage.js
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/index.jsx
Labels: bug

#592 Fixed an issue with GET parameters inside of coupon deeplinks
  libraries/commerce/cart/streams/index.js
Labels: bug

#595 Added possibility to implement custom UI for product options
  libraries/commerce/product/selectors/options.js
  themes/theme-gmd/pages/Product/components/Content/connector.js
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/Discount/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Price/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/PriceInfo/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/PriceStriked/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/Tiers/connector.js
  themes/theme-gmd/pages/Product/components/Options/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Options/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Options/components/Content/connector.js
  themes/theme-gmd/pages/Product/components/Options/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/Content/spec.jsx
  themes/theme-gmd/pages/Product/components/Options/components/Option/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/spec.jsx
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/index.jsx
  themes/theme-gmd/pages/Product/components/Options/index.jsx
  themes/theme-gmd/pages/Product/components/Options/spec.jsx
  themes/theme-gmd/themeApi/index.js
  themes/theme-ios11/pages/Product/components/Content/connector.js
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/Discount/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Price/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Price/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/PriceInfo/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/PriceStriked/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/Tiers/connector.js
  themes/theme-ios11/pages/Product/components/Options/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Options/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Options/components/Content/connector.js
  themes/theme-ios11/pages/Product/components/Options/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/Content/spec.jsx
  themes/theme-ios11/pages/Product/components/Options/components/Option/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/spec.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/index.jsx
  themes/theme-ios11/pages/Product/components/Options/index.jsx
  themes/theme-ios11/pages/Product/components/Options/spec.jsx
  themes/theme-ios11/themeApi/index.js
Labels: enhancement

#596 Open social media app deeplinks natively
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/common/subscriptions/helpers/handleLinks.spec.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
  themes/theme-gmd/widgets/Html/connector.js
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/connector.js
  themes/theme-ios11/widgets/Html/index.jsx
Labels: bug

#597 Added a camera permission check before the scanner route is opened
  libraries/commerce/scanner/actions/grantCameraPermissions.js
  libraries/commerce/scanner/actions/grantCameraPermissions.spec.js
  libraries/core/classes/ScannerManager/index.js
  libraries/core/commands/__tests__/openAppSettings.spec.js
  libraries/core/commands/appPermissions.js
  libraries/core/commands/openAppSettings.js
  libraries/core/constants/AppEvents.js
  libraries/core/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/pages/subscriptions.js
Labels: enhancement

#601 Automated changelog creation
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Makefile
  package.json
  scripts/build-changelog.js
  themes/theme-gmd/CHANGELOG.md
  themes/theme-ios11/CHANGELOG.md
Labels: enhancement

#599 Fix for customizing theme colors
  libraries/common/helpers/config/theme.js
Labels: bug

#600 Fallback to null when no shipping is given
  libraries/commerce/cart/helpers/shipping.js
  libraries/commerce/cart/selectors/index.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/index.jsx
Labels: bug

#602 Small refactoring of the changelog builder script
  .github/PULL_REQUEST_TEMPLATE.md
  scripts/build-changelog.js
Labels: polish

#604 Open social media app deeplinks natively
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/common/subscriptions/helpers/handleLinks.spec.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
  themes/theme-gmd/widgets/Html/connector.js
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/connector.js
  themes/theme-ios11/widgets/Html/index.jsx
Labels: bug

#603 Add coupon + product to cart when QR code is scanned
  libraries/commerce/cart/constants/index.js
  libraries/commerce/cart/streams/index.js
  libraries/commerce/cart/streams/index.spec.js
  libraries/commerce/cart/subscriptions/index.js
  libraries/commerce/cart/subscriptions/index.spec.js
  libraries/commerce/checkout/index.js
  libraries/commerce/scanner/actions/handleQrCode.js
  libraries/commerce/scanner/helpers/index.js
  libraries/commerce/scanner/helpers/index.spec.js
Labels: bug

#607 Added missing french translation for search placeholder
  themes/theme-gmd/locale/fr-FR.json
Labels: bug

#606 Extended the scanner event listeners to register for specific payload formats
  libraries/commerce/scanner/constants/index.js
  libraries/commerce/scanner/streams/index.js
  libraries/commerce/scanner/streams/index.spec.js
  libraries/commerce/scanner/subscriptions/index.js
  libraries/commerce/scanner/subscriptions/index.spec.js
  libraries/core/classes/Scanner/index.js
  libraries/core/classes/Scanner/index.spec.js
  libraries/core/classes/ScannerEventHandler/index.js
  libraries/core/classes/ScannerEventHandler/index.spec.js
  libraries/core/classes/ScannerEventListener/index.js
  libraries/core/classes/ScannerEventListener/index.spec.js
  libraries/core/constants/Scanner.js
  libraries/tracking/helpers/index.js
Labels: bug, enhancement

#609 Removed duplicate getUserLogin selector
  libraries/common/selectors/user.js
Labels: polish

#614 Keep shipping costs selector
  libraries/commerce/cart/selectors/index.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/connector.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/ShippingCosts/connector.js
Labels: bug

#611 Avoid screen overflow for select form element
  libraries/ui-shared/Form/Builder/index.jsx
  libraries/ui-shared/Form/Builder/iso-3166-2.js
  libraries/ui-shared/Form/Select/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/Select/style.js
Labels: bug

#610 Avoid screen overflow for select form element
  libraries/ui-shared/Form/Builder/index.jsx
  libraries/ui-shared/Form/Builder/iso-3166-2.js
  libraries/ui-shared/Form/Select/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/Select/style.js
Labels: bug

#612 Ignore unknown country in form builder country field
  libraries/ui-shared/Form/Builder/builders/buildCountryList.js
  libraries/ui-shared/Form/Builder/builders/buildCountryList.spec.js
Labels: bug

#613 Ignore unknown country in form builder country field
  libraries/ui-shared/Form/Builder/builders/buildCountryList.js
  libraries/ui-shared/Form/Builder/builders/buildCountryList.spec.js
Labels: bug

#615 Improved rendering of videos within product descriptions and the HTML widget
  libraries/common/collections/media-providers/MediaProvider.js
  libraries/common/collections/media-providers/MediaProvider.spec.js
  libraries/common/collections/media-providers/Vimeo.js
  libraries/common/collections/media-providers/Vimeo.spec.js
  libraries/common/collections/media-providers/YouTube.js
  libraries/common/collections/media-providers/YouTube.spec.js
  libraries/common/collections/media-providers/__snapshots__/MediaProvider.spec.js.snap
  libraries/common/collections/media-providers/index.js
  libraries/common/collections/media-providers/style.js
  libraries/common/components/HtmlSanitizer/__snapshots__/spec.jsx.snap
  libraries/common/components/HtmlSanitizer/index.jsx
  libraries/common/components/HtmlSanitizer/spec.jsx
  themes/theme-gmd/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Description/connector.js
  themes/theme-gmd/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Html/connector.js
  themes/theme-gmd/widgets/Html/index.jsx
  themes/theme-gmd/widgets/Html/spec.jsx
  themes/theme-ios11/pages/Product/components/Description/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Description/connector.js
  themes/theme-ios11/widgets/Html/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Html/connector.js
  themes/theme-ios11/widgets/Html/index.jsx
  themes/theme-ios11/widgets/Html/spec.jsx
  yarn.lock
Labels: enhancement

#618 Add missing country ME
  libraries/ui-shared/Form/Builder/builders/buildCountryList.spec.js
  libraries/ui-shared/Form/Builder/iso-3166-2.js
Labels: bug

#616 Add theme, router and current product, React Hooks and HOC to easily access the appropriate data
  extensions/@shopgate-product-reviews/frontend/package.json
  libraries/engage/core/hocs/withCurrentProduct.jsx
  libraries/engage/core/hocs/withRoute.jsx
  libraries/engage/core/hocs/withTheme.jsx
  libraries/engage/core/hooks/useCurrentProduct.js
  libraries/engage/core/hooks/useRoute.js
  libraries/engage/core/hooks/useTheme.js
  libraries/engage/core/index.js
  libraries/engage/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
Labels: enhancement

#620 Fixed scanner route redirects
  libraries/engage/scanner/index.js
  libraries/engage/scanner/index.spec.js
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-gmd/pages/subscriptions.spec.js
  themes/theme-ios11/pages/subscriptions.js
  themes/theme-ios11/pages/subscriptions.spec.js
Labels: internal

#621 Fixed broken handling of channel urls
  libraries/common/subscriptions/helpers/handleLinks.js
Labels: bug

#617 Added Minimum Advertising Pricing (MAP) support in Engage
  libraries/commerce/product/constants/Portals.js
  libraries/commerce/product/constants/index.js
  libraries/commerce/product/helpers/mapPrice.js
  libraries/commerce/product/hocs/withMapPricing.jsx
  libraries/commerce/product/hocs/withMapPricing.spec.js
  libraries/commerce/product/hocs/withPriceCalculation.jsx
  libraries/commerce/product/hocs/withPriceCalculation.spec.js
  libraries/commerce/product/mock.js
  libraries/commerce/product/selectors/price.js
  libraries/commerce/product/selectors/price.spec.js
  libraries/common/components/TimeBoundary/index.jsx
  libraries/common/components/TimeBoundary/spec.jsx
  libraries/common/helpers/date/index.js
  libraries/common/helpers/date/spec.js
  libraries/common/streams/interval.js
  libraries/engage/components/index.js
  libraries/ui-shared/MapPriceHint/connector.js
  libraries/ui-shared/MapPriceHint/index.jsx
  libraries/ui-shared/MapPriceHint/style.js
  themes/theme-gmd/components/ProductCard/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemDetails/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemDetails/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Item/components/ItemPrice/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/ProductGridPrice/index.jsx
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/pages/Product/components/Header/components/PriceStriked/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemDetails/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Item/components/ItemPrice/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGridPrice/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/components/ProductGridPrice/index.jsx
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/pages/Product/components/Header/components/PriceStriked/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
Labels: enhancement

#623 Fixed the Scanner to directly open the found item, when the search result only contains one item
  libraries/commerce/scanner/actions/handleBarCode.js
  libraries/commerce/scanner/actions/handleBarCode.spec.js
  libraries/commerce/scanner/actions/handleNoResults.js
  libraries/commerce/scanner/actions/handleNoResults.spec.js
  libraries/commerce/scanner/actions/handleQrCode.js
  libraries/commerce/scanner/actions/handleQrCode.spec.js
  libraries/commerce/scanner/actions/handleSearch.js
  libraries/commerce/scanner/actions/handleSearch.spec.js
Labels: bug

#625 Fixed an issue with scanning QR Code links that lead to non existent pages
  libraries/commerce/category/reducers/categoriesById.js
  libraries/commerce/category/reducers/childrenByCategoryId.js
  libraries/commerce/product/action-creators/errorProducts.js
  libraries/commerce/product/actions/fetchProducts.js
  libraries/commerce/product/reducers/productsById.js
  libraries/common/action-creators/page/index.js
  libraries/common/action-creators/page/spec.js
  libraries/common/actions/page/fetchPageConfig.js
  libraries/common/reducers/page/index.js
  themes/theme-gmd/pages/Category/streams.js
  themes/theme-gmd/pages/Category/streams.spec.js
  themes/theme-gmd/pages/Category/subscriptions.js
  themes/theme-gmd/pages/Page/components/Content/index.jsx
  themes/theme-ios11/pages/Category/streams.js
  themes/theme-ios11/pages/Category/streams.spec.js
  themes/theme-ios11/pages/Category/subscriptions.js
  themes/theme-ios11/pages/Page/components/Content/index.jsx
Labels: bug

#624 Added support for Portuguese language.
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#627 Replaced scanner flash icon for disabled flashlight to make it more clear what it does
  libraries/engage/components/index.js
  libraries/ui-shared/ScannerOverlay/__snapshots__/index.spec.jsx.snap
  libraries/ui-shared/ScannerOverlay/components/ScannerBar/components/FlashlightButton/index.jsx
  libraries/ui-shared/icons/FlashDisabledIcon.jsx
  libraries/ui-shared/icons/FlashEnabledIcon.jsx
  libraries/ui-shared/icons/FlashOffIcon.jsx
Labels: enhancement

#622 Implemented translation system for cart and cart item messages.
  libraries/ui-shared/MessageBar/__snapshots__/spec.jsx.snap
  libraries/ui-shared/MessageBar/index.jsx
  libraries/ui-shared/MessageBar/spec.jsx
Labels: enhancement

#628 Added rxjs operator `mergeMap` to the main stream
  libraries/common/streams/main.js
Labels: bug

#631 Added extensibility of the app footer
  libraries/common/constants/Portals.js
  libraries/common/helpers/dom/index.js
  libraries/common/helpers/dom/index.spec.js
  libraries/engage/package.json
  libraries/ui-material/SnackBar/index.jsx
  libraries/ui-shared/Footer/__snapshots__/index.spec.jsx.snap
  libraries/ui-shared/Footer/index.jsx
  libraries/ui-shared/Footer/index.spec.jsx
  libraries/ui-shared/Footer/style.js
  libraries/ui-shared/ScannerOverlay/__snapshots__/index.spec.jsx.snap
  libraries/ui-shared/ScannerOverlay/components/ScannerBar/index.jsx
  libraries/ui-shared/ScannerOverlay/components/ScannerBar/style.js
  libraries/ui-shared/ScannerOverlay/index.spec.jsx
  themes/theme-gmd/components/View/index.jsx
  themes/theme-gmd/components/View/style.js
  themes/theme-gmd/components/Viewport/index.jsx
  themes/theme-gmd/components/Viewport/style.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/style.js
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/components/TabBar/style.js
  themes/theme-ios11/components/View/index.jsx
  themes/theme-ios11/components/View/style.js
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/components/Viewport/style.js
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/style.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/style.js
Labels: enhancement

#630 Navigation functions can be injected via React Hooks and HOCs.
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-tracking-ga-native/frontend/package.json
  extensions/@shopgate-user-privacy/frontend/package.json
  jest.config.js
  libraries/common/context/index.js
  libraries/common/package.json
  libraries/engage/README.md
  libraries/engage/components/NavigationHandler/__snapshots__/spec.jsx.snap
  libraries/engage/components/NavigationHandler/connector.js
  libraries/engage/components/NavigationHandler/index.jsx
  libraries/engage/components/NavigationHandler/spec.jsx
  libraries/engage/components/index.js
  libraries/engage/core/hocs/withNavigation.jsx
  libraries/engage/core/hooks/__tests__/useNavigation.spec.js
  libraries/engage/core/hooks/useNavigation.js
  libraries/engage/core/index.js
  libraries/engage/core/router/__tests__/helpers.spec.js
  libraries/engage/core/router/helpers.js
  libraries/engage/package.json
  libraries/tracking-core/package.json
  package.json
  themes/theme-gmd/package.json
  themes/theme-gmd/pages/index.jsx
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/index.jsx
  utils/unit-tests/package.json
  yarn.lock
Labels: enhancement

#632 Fixed inconsistent UI logged in state when a getUser request failed
  libraries/common/actions/user/fetchUser.js
  libraries/common/actions/user/login.js
  themes/theme-gmd/components/NavDrawer/components/Header/connector.js
  themes/theme-gmd/components/NavDrawer/components/Header/index.jsx
Labels: bug

#629 Introduced a configuration to limit favorite list item count
  Makefile
  libraries/commerce/favorites/action-creators/index.js
  libraries/commerce/favorites/actions/fetchFavorites.js
  libraries/commerce/favorites/actions/spec.js
  libraries/commerce/favorites/actions/toggleFavorites.js
  libraries/commerce/favorites/constants/index.js
  libraries/commerce/favorites/reducers/products.js
  libraries/commerce/favorites/streams/index.js
  libraries/commerce/favorites/subscriptions/index.js
  libraries/commerce/favorites/subscriptions/spec.js
  libraries/common/helpers/config/index.js
  libraries/common/streams/main.js
  libraries/core/constants/Pipeline.js
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: bug

#634 The ProductGrid component is now part of the Theme API
  themes/theme-gmd/themeApi/index.js
  themes/theme-ios11/themeApi/index.js
Labels: enhancement

#633 The Swiper items now have equal heights
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#635 Corrected the cart total discount label from plural to singular
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/Discounts/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/Discounts/index.jsx
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/Discounts/spec.jsx
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/Discounts/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/Discounts/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/Discounts/spec.jsx
Labels: bug

#636 Corrected login.email translations for locales nl-NL and fr-FR.
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/nl-NL.json
Labels: bug

#637 Added Portals around the Tax Component within the PaymentBar
  libraries/commerce/cart/constants/Portals.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/Tax/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/Tax/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/Tax/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/Tax/index.jsx
Labels: enhancement

#640 Update tax and shipping disclaimers translations
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
Labels: polish

#639 Update tax and shipping disclaimers translations
  themes/theme-gmd/e2e/integration/consistency/CartPage.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: polish
