Repository shopgate/pwa, pull requests merged in 2019-02, with the labels that each got.

#518 Provide the ProductContext via the Theme API
  themes/theme-gmd/pages/themeApi.js
  themes/theme-ios11/pages/themeApi.js
Labels: enhancement

#517 Added props to the store info section portals of the NavDrawer
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/ImprintButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/PaymentButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/PrivacyButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/ReturnsButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/ShippingButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/components/TermsButton/index.jsx
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedIn/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/index.spec.jsx
  themes/theme-ios11/pages/More/style.js
Labels: bug, enhancement

#519 Updated Conductor in favor of a bug fix with resetting the router stack.
  libraries/common/package.json
  libraries/common/reducers/router/index.js
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#515 v.5.X Force refresh product stock information after checkout
  .travis.yml
  libraries/commerce/cart/subscriptions/index.js
  libraries/commerce/checkout/action-creators/successCheckout.js
  libraries/commerce/checkout/constants/index.js
  libraries/commerce/checkout/streams/index.js
  libraries/commerce/checkout/subscriptions/index.js
  libraries/commerce/product/action-creators/expireProductById.js
  libraries/commerce/product/constants/index.js
  libraries/commerce/product/reducers/descriptionsByProductId.js
  libraries/commerce/product/reducers/imagesByProductId.js
  libraries/commerce/product/reducers/optionsByProductId.js
  libraries/commerce/product/reducers/productsById.js
  libraries/commerce/product/reducers/propertiesByProductId.js
  libraries/commerce/product/reducers/resultsByHash.js
  libraries/commerce/product/reducers/shippingByProductId.js
  libraries/commerce/product/reducers/variantsByProductId.js
  libraries/commerce/product/subscriptions/index.js
  themes/theme-gmd/pages/subscribers.js
  themes/theme-ios11/pages/subscribers.js
Labels: enhancement

#522 Fix White page on selecting certain input option (select option)
  libraries/commerce/product/reducers/helpers/formatOptions.js
  libraries/commerce/product/reducers/helpers/formatOptions.spec.js
  libraries/commerce/product/selectors/options.js
  libraries/ui-shared/Form/Builder/classes/ActionListener/index.jsx
  package.json
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/index.jsx
  utils/benchmark/index.js
Labels: bug

#524 Added portals to the PaymentBar component.
  libraries/commerce/cart/constants/Portals.js
  themes/theme-gmd/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/index.jsx
  themes/theme-ios11/pages/Cart/components/PaymentBar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/index.jsx
Labels: enhancement

#525 Added additional translations for user-privacy extension
  extensions/@shopgate-user-privacy/extension-config.json
  extensions/@shopgate-user-privacy/frontend/locale/es-ES.json
  extensions/@shopgate-user-privacy/frontend/locale/it-IT.json
Labels: enhancement

#526 Fixed the possibility of adding spaces to the end of a search term
  themes/theme-gmd/components/Search/index.jsx
Labels: bug

#527 Merged latest planned release into current feature branch.
  CHANGELOG.md
  Makefile
  extensions/@shopgate-product-reviews/extension-config.json
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-tracking-ga-native/extension-config.json
  extensions/@shopgate-tracking-ga-native/frontend/package.json
  extensions/@shopgate-user-privacy/extension-config.json
  extensions/@shopgate-user-privacy/frontend/package.json
  lerna.json
  libraries/commerce/package.json
  libraries/common/package.json
  libraries/core/package.json
  libraries/tracking-core/package.json
  libraries/tracking/package.json
  libraries/ui-ios/package.json
  libraries/ui-material/package.json
  libraries/ui-shared/package.json
  libraries/webcheckout/package.json
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/package.json
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/package.json
  utils/benchmark/package.json
  utils/e2e/package.json
  utils/eslint-config/package.json
  utils/unit-tests/package.json
Labels: enhancement

#531 Fixed a bug where the router throws an error when running a theme in standalone.
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#532 Fixed wrong tracking events
  libraries/common/components/Slider/__snapshots__/spec.jsx.snap
  libraries/common/selectors/history.js
  libraries/tracking/selectors/page.js
  libraries/tracking/streams/category.spec.js
  libraries/tracking/streams/product.spec.js
  libraries/tracking/streams/search.spec.js
  themes/theme-gmd/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/WriteReview/components/ReviewForm/components/FormButtons/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/TabBar/selectors.spec.js
  themes/theme-ios11/pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/WriteReview/components/ReviewForm/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/WriteReview/components/ReviewForm/components/FormButtons/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#529 Enable parent product cart button when it has variants to select
  .eslintignore
  libraries/commerce/product/selectors/product.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/connector.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/connector.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/connector.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
Labels: bug

#528 Enable parent product cart button when it has variants to select
  libraries/ui-shared/AddToCartButton/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
Labels: bug

#533 Improve commerce/product/getBaseProductId selector
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/selectors/product.spec.js
Labels: bug

#538 Added missing props to the ProductCard from the themeApi
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/index.jsx
  themes/theme-gmd/themeApi/ProductCard/components/Render/index.spec.jsx
  themes/theme-gmd/themeApi/ProductCard/index.jsx
  themes/theme-gmd/themeApi/ProductCard/index.spec.jsx
  themes/theme-gmd/themeApi/ProductCard/mock.js
  themes/theme-gmd/widgets/Liveshopping/components/Item/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/index.jsx
  themes/theme-ios11/themeApi/ProductCard/components/Render/index.spec.jsx
  themes/theme-ios11/themeApi/ProductCard/index.jsx
  themes/theme-ios11/themeApi/ProductCard/index.spec.jsx
  themes/theme-ios11/themeApi/ProductCard/mock.js
  themes/theme-ios11/widgets/Liveshopping/components/Item/index.jsx
Labels: bug, enhancement

#539 The AppBar in iOS is only rendered when its target container has mounted
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
Labels: bug

#536 Check issues of Browser Connector with Cypress Tests
  .eslintignore
  Makefile
  themes/theme-gmd/e2e/cypress.json
  themes/theme-gmd/e2e/helper/cart.js
  themes/theme-gmd/e2e/integration/consistency/CartPage.js
  themes/theme-gmd/e2e/integration/consistency/CartPageCoupon.js
  themes/theme-gmd/e2e/integration/functional/CartPage.js
  themes/theme-gmd/e2e/integration/functional/CartPageCoupon.js
  themes/theme-gmd/e2e/integration/functional/CartPageOptions.js
  themes/theme-gmd/e2e/integration/functional/CategoryPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-gmd/e2e/integration/functional/ProductPage.js
  themes/theme-gmd/e2e/integration/functional/ProductPageOptions.js
  utils/e2e/plugins/index.js
  utils/e2e/support/commands.js
  utils/e2e/support/index.js
Labels: enhancement

#540 Wrong page tracked when user comes back after checkout
  libraries/common/reducers/router/index.js
  libraries/common/streams/main.js
  libraries/tracking/action-creators/index.js
  libraries/tracking/constants/index.js
  libraries/tracking/helpers/index.js
  libraries/tracking/helpers/index.spec.js
  libraries/tracking/streams/app.js
  libraries/tracking/streams/checkout.js
  libraries/tracking/streams/pages.js
  libraries/tracking/streams/pages.spec.js
  libraries/tracking/subscriptions/checkout.js
  libraries/tracking/subscriptions/checkout.spec.js
  libraries/tracking/subscriptions/setup.js
  libraries/tracking/subscriptions/setup.spec.js
Labels: bug

#543 Fix for text hint below text input options with zero rendered price
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/components/OptionInfo/spec.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/components/OptionInfo/spec.jsx
Labels: bug

#542 Show variants modal selection on favorite list when product has options
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/selectors/product.spec.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/connector.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/connector.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
Labels: bug

#547 Fixed broken disabled characteristic sheet items on iOS
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-tracking-ga-native/frontend/package.json
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/SheetItem/style.js
  utils/unit-tests/package.json
  yarn.lock
Labels: bug

#545 Fixed broken cart layout at long availability texts
  libraries/ui-shared/ProductProperties/__snapshots__/index.spec.jsx.snap
  libraries/ui-shared/ProductProperties/index.jsx
  libraries/ui-shared/ProductProperties/index.spec.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/style.js
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/style.js
Labels: bug

#546 Fixed broken cart layout at long availability texts
  libraries/ui-shared/ProductProperties/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/style.js
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/components/Properties/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/style.js
Labels: bug

#544 Added the possibility of handling a pipeline error response containing multiple errors
  extensions/@shopgate-product-reviews/frontend/package.json
  extensions/@shopgate-tracking-ga-native/frontend/package.json
  libraries/commerce/cart/action-creators/errorAddCouponsToCart.js
  libraries/commerce/cart/action-creators/errorAddProductsToCart.js
  libraries/commerce/cart/action-creators/errorDeleteCouponsFromCart.js
  libraries/commerce/cart/action-creators/errorDeleteProductsFromCart.js
  libraries/commerce/cart/action-creators/errorUpdateProductsInCart.js
  libraries/commerce/cart/actions/addCouponsToCart.js
  libraries/commerce/cart/actions/addProductsToCart.js
  libraries/commerce/cart/actions/deleteCouponsFromCart.js
  libraries/commerce/cart/actions/deleteProductsFromCart.js
  libraries/commerce/cart/actions/updateProductsInCart.js
  libraries/commerce/cart/constants/PipelineErrors.js
  libraries/commerce/cart/helpers/createPipelineErrorList.js
  libraries/commerce/cart/streams/index.js
  libraries/commerce/cart/subscriptions/index.js
  libraries/core/classes/PipelineManager/index.js
  libraries/core/constants/Pipeline.js
  libraries/ui-shared/Dialog/components/PipelineErrorDialog/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Dialog/components/PipelineErrorDialog/index.jsx
  package.json
  utils/unit-tests/package.json
  yarn.lock
Labels: enhancement

#550 Cleaned up Portal positions
  libraries/common/constants/Portals.js
  themes/theme-gmd/pages/Cart/components/Item/components/Coupon/components/Layout/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
Labels: enhancement

#549 Fix e2e tests. Run tests by webhook
  Makefile
  scripts/githubJenkinsParser.js
  themes/theme-gmd/e2e/helper/category.js
  themes/theme-gmd/e2e/integration/consistency/CategoryPage.js
  themes/theme-gmd/e2e/integration/consistency/ProductPage.js
  themes/theme-gmd/e2e/integration/functional/CartPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/index.jsx
Labels: bug

#548 Selecting a Product Variant does not replace the route anymore.
  libraries/commerce/product/streams/index.js
  libraries/commerce/product/streams/index.spec.js
  libraries/commerce/product/subscriptions/index.js
  libraries/common/components/ProductCharacteristics/connector.js
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/common/helpers/router/index.js
  libraries/common/streams/router.js
  libraries/tracking/streams/product.js
  libraries/tracking/streams/product.spec.js
  libraries/tracking/subscriptions/product.js
  themes/theme-gmd/components/ProductImage/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductImage/style.js
  themes/theme-gmd/pages/Product/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/components/ProductImage/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductImage/style.js
  themes/theme-ios11/pages/Product/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
Labels: enhancement

#551 Implement sentry.io for javascript error logging for engage app
  libraries/common/App.jsx
  libraries/common/actions/router/historyPop.js
  libraries/common/components/ErrorBoundary/connector.js
  libraries/common/components/ErrorBoundary/index.jsx
  libraries/common/components/Route/index.jsx
  libraries/common/helpers/config/index.js
  libraries/common/package.json
  libraries/common/subscriptions/error.js
  libraries/core/classes/PipelineManager/spec.js
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/pages/subscribers.js
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/pages/subscribers.js
  yarn.lock
Labels: enhancement

#554 Implement sentry.io for javascript error logging for engage app
  libraries/common/App.jsx
  libraries/common/actions/router/historyPop.js
  libraries/common/components/ErrorBoundary/connector.js
  libraries/common/components/ErrorBoundary/index.jsx
  libraries/common/components/Route/index.jsx
  libraries/common/helpers/config/index.js
  libraries/common/package.json
  libraries/common/subscriptions/error.js
  libraries/core/classes/PipelineManager/spec.js
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/pages/subscribers.js
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/pages/subscribers.js
  yarn.lock
Labels: enhancement

#555 Improve error behaviour for tracking core plugin calls
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/error.js
  libraries/core/classes/ErrorManager/index.js
  libraries/core/classes/ErrorManager/spec.js
  libraries/core/classes/PipelineManager/index.js
  libraries/core/constants/ErrorManager.js
  libraries/tracking-core/core/Core.js
  libraries/tracking/subscriptions/setup.js
Labels: enhancement

#558 Fix PRODUCT_ITEM_PRICE_AFTER Portal positioning
  themes/theme-gmd/components/ProductCard/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/components/ProductCard/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
Labels: bug

#556 Correct handling of concurrent cart requests when adding a coupon with deeplink
  libraries/commerce/cart/subscriptions/index.js
  libraries/core/commands/registerEvents.js
Labels: bug

#557 Expire page configs on every app start
  libraries/common/actions/page/fetchPageConfig.js
  libraries/common/reducers/page/index.js
  themes/theme-gmd/pages/StartPage/subscriptions.js
  themes/theme-ios11/pages/StartPage/subscriptions.js
Labels: bug
