Repository shopgate/pwa, pull requests merged in 2019-10, with the labels that each got.

#840 New theme config "product.variantPreselect" is added.
  libraries/common/components/ProductCharacteristics/helpers/index.js
  libraries/common/components/ProductCharacteristics/helpers/index.spec.js
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/common/helpers/config/index.js
  libraries/common/reducers/page/index.js
  libraries/engage/product/components/ProductCharacteristics/helpers/index.js
  libraries/engage/product/components/ProductCharacteristics/helpers/index.spec.js
  libraries/engage/product/components/ProductCharacteristics/index.jsx
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/extension-config.json
Labels: enhancement

#842 Fixed flickering pdp ui elements on iOS 13
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#845 Replaced IOS TabBar icons for consistent sized ones and removed redundant viewBox definitions.
  libraries/common/helpers/config/mock.js
  libraries/ui-ios/icons/CartIcon.jsx
  libraries/ui-ios/icons/HomeIcon.jsx
  libraries/ui-shared/ScannerOverlay/__snapshots__/index.spec.jsx.snap
  libraries/ui-shared/icons/BarcodeScannerIcon.jsx
  libraries/ui-shared/icons/BrowseIcon.jsx
  libraries/ui-shared/icons/FlashDisabledIcon.jsx
  libraries/ui-shared/icons/FlashEnabledIcon.jsx
  libraries/ui-shared/icons/MoreIcon.jsx
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/components/TabBar/components/CartAction/style.js
  themes/theme-ios11/components/TabBar/components/FavoritesAction/style.js
  themes/theme-ios11/components/TabBar/components/HomeAction/style.js
  themes/theme-ios11/components/TabBar/components/MoreAction/style.js
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
Labels: bug

#846 Move Shadow config for App bar to App Bar component settings
  libraries/common/helpers/config/mock.js
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartBadge/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartBadge/spec.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartBadge/style.js
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/components/AppBar/components/CartButton/components/CartBadge/index.jsx
  themes/theme-ios11/components/AppBar/components/CartButton/components/CartBadge/spec.jsx
  themes/theme-ios11/extension-config.json
Labels: bug

#847 Fixed history imports to eliminate error warnings.
  libraries/common/helpers/router/index.js
  libraries/common/package.json
  libraries/engage/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#848 Show generic message for irrelevant errors as toast messages
  libraries/common/package.json
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/error.js
  libraries/common/subscriptions/helpers/pipeline.js
  libraries/common/subscriptions/helpers/pipeline.spec.js
  libraries/core/classes/ErrorManager/index.js
  libraries/core/classes/ErrorManager/spec.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: polish

#849 Improved extensibility of CTA button portals
  libraries/engage/product/components/MediaSlider/style.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/CTAButtons/style.js
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/index.jsx
Labels: bug

#850 Implemented a way to extend and replace actions and updated public action definitions for mutability.
  Makefile
  libraries/commerce/cart/actions/addCouponsToCart.js
  libraries/commerce/cart/actions/addProductsToCart.js
  libraries/commerce/cart/actions/deleteCouponsFromCart.js
  libraries/commerce/cart/actions/deleteProductsFromCart.js
  libraries/commerce/cart/actions/fetchCart.js
  libraries/commerce/cart/actions/updateProductsInCart.js
  libraries/commerce/category/actions/fetchCategory.js
  libraries/commerce/category/actions/fetchCategoryChildren.js
  libraries/commerce/category/actions/fetchCategoryProducts.js
  libraries/commerce/category/actions/fetchRootCategories.js
  libraries/commerce/checkout/actions/fetchCheckoutUrl.js
  libraries/commerce/favorites/actions/fetchFavorites.js
  libraries/commerce/favorites/actions/toggleFavorites.js
  libraries/commerce/product/actions/fetchProduct.js
  libraries/commerce/product/actions/fetchProductDescription.js
  libraries/commerce/product/actions/fetchProductImages.js
  libraries/commerce/product/actions/fetchProductMedia.js
  libraries/commerce/product/actions/fetchProductOptions.js
  libraries/commerce/product/actions/fetchProductProperties.js
  libraries/commerce/product/actions/fetchProductRelations.js
  libraries/commerce/product/actions/fetchProductShipping.js
  libraries/commerce/product/actions/fetchProductVariants.js
  libraries/commerce/reviews/actions/fetchProductReviews.js
  libraries/commerce/reviews/actions/fetchReviews.js
  libraries/commerce/reviews/actions/fetchUserReview.js
  libraries/commerce/reviews/actions/flushUserReview.js
  libraries/commerce/reviews/actions/submitReview.js
  libraries/commerce/search/actions/fetchSearchResults.js
  libraries/commerce/search/actions/fetchSearchSuggestions.js
  libraries/common/actions/modal/closeModal.js
  libraries/common/actions/modal/showModal.js
  libraries/common/actions/page/fetchPageConfig.js
  libraries/common/actions/router/historyPop.js
  libraries/common/actions/router/historyPush.js
  libraries/common/actions/router/historyReplace.js
  libraries/common/actions/router/historyReset.js
  libraries/common/actions/user/fetchRegisterUrl.js
  libraries/common/actions/user/fetchUser.js
  libraries/common/actions/user/login.js
  libraries/common/actions/user/logout.js
  libraries/common/helpers/redux/__tests__/compareObjects.spec.js
  libraries/common/helpers/redux/__tests__/generateSortedHash.spec.js
  libraries/common/helpers/redux/__tests__/mutable.spec.js
  libraries/common/helpers/redux/compareObjects.js
  libraries/common/helpers/redux/generateResultHash.js
  libraries/common/helpers/redux/generateSortedHash.js
  libraries/common/helpers/redux/hasExpired.js
  libraries/common/helpers/redux/index.js
  libraries/common/helpers/redux/mutable.js
  libraries/common/helpers/redux/shouldFetchData.js
  libraries/common/helpers/redux/shouldFetchFilters.js
  libraries/common/helpers/redux/spec.js
Labels: enhancement

#852 Refactored category selectors
  libraries/commerce/category/selectors/index.js
  libraries/commerce/category/selectors/index.spec.js
  libraries/commerce/scanner/actions/handleQrCode.js
  libraries/commerce/scanner/actions/handleQrCode.spec.js
  libraries/tracking/selectors/category.js
  themes/theme-gmd/components/FilterBar/components/Content/selectors.js
  themes/theme-gmd/pages/Category/components/CategoryListContent/connector.js
  themes/theme-gmd/pages/Category/components/Content/connector.js
  themes/theme-gmd/pages/Category/components/Empty/selectors.js
  themes/theme-gmd/widgets/selectors.js
  themes/theme-ios11/components/FilterBar/components/Content/selectors.js
  themes/theme-ios11/pages/Category/components/CategoryListContent/connector.js
  themes/theme-ios11/pages/Category/components/Content/connector.js
  themes/theme-ios11/pages/Category/components/Empty/selectors.js
  themes/theme-ios11/widgets/selectors.js
Labels: enhancement
