Repository shopgate/pwa, pull requests merged in 2019-11, with the labels that each got.

#853 Updated react-spring module to the latest version
  libraries/ui-material/SnackBar/index.jsx
  libraries/ui-material/package.json
  yarn.lock
Labels: enhancement

#854 Fixed wrong expires calculation for resultsByHash reducer
  libraries/commerce/product/reducers/resultsByHash.js
Labels: bug

#855 Fixed an issue where the cart loading indicator didn't stop
  libraries/commerce/cart/subscriptions/index.js
  libraries/common/providers/loading/index.jsx
  libraries/common/providers/loading/index.spec.jsx
  themes/theme-gmd/e2e/elements/de.js
Labels: bug

#859 A11y: Live messages are cleared after reading
  libraries/common/components/ProductCharacteristics/index.jsx
  libraries/engage/a11y/components/LiveMessenger/__tests__/helpers.spec.js
  libraries/engage/a11y/components/LiveMessenger/helpers.js
  libraries/engage/product/components/ProductCharacteristics/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-gmd/pages/Favorites/subscriptions.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/index.jsx
  themes/theme-gmd/pages/Product/components/Options/components/TextOption/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/CTAButtons/index.jsx
  themes/theme-ios11/pages/Favorites/subscriptions.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/index.jsx
  themes/theme-ios11/pages/Product/components/Options/components/TextOption/index.jsx
Labels: bug

#857 Improved a11y labels of price range filter chips
  themes/theme-gmd/components/FilterBar/components/Content/components/FilterChips/index.jsx
  themes/theme-ios11/components/FilterBar/components/Content/components/FilterChips/index.jsx
Labels: enhancement

#858 Added noCache param to language config. To avoid outdated language settings
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/extension-config.json
Labels: bug

#860 Improved a11y of the SelectBox component
  libraries/common/components/SelectBox/__snapshots__/spec.jsx.snap
  libraries/common/components/SelectBox/components/Item/index.jsx
  libraries/common/components/SelectBox/index.jsx
Labels: enhancement

#861 A11y: Enhanced hidden price range filter inputs with a currency symbol
  libraries/engage/filter/components/PriceSlider/components/Label/__snapshots__/spec.jsx.snap
  libraries/engage/filter/components/PriceSlider/components/Label/index.jsx
Labels: enhancement

#864 Removed SnackBar button from a11y tree
  libraries/ui-material/SnackBar/index.jsx
Labels: bug

#865 Error handling: Generic error didn't appear for "EBIGAPI"
  libraries/common/subscriptions/error.js
  libraries/core/classes/ErrorManager/index.js
  themes/theme-gmd/pages/subscriptions.js
  themes/theme-ios11/pages/subscriptions.js
Labels: internal

#863 A11y: fix a cart item quantity to read before item name
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/style.js
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/style.js
Labels: bug

#866 Enabled the TabBar of the iOS theme for screen readers (a11y)
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartButton/index.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/components/AppBar/presets/DefaultBar/connector.js
  themes/theme-ios11/components/TabBar/components/BrowseAction/index.jsx
  themes/theme-ios11/components/TabBar/components/CartAction/components/CartItemBadge/connector.js
  themes/theme-ios11/components/TabBar/components/CartAction/index.jsx
  themes/theme-ios11/components/TabBar/components/FavoritesAction/components/FavoritesIconBadge/index.jsx
  themes/theme-ios11/components/TabBar/components/FavoritesAction/index.jsx
  themes/theme-ios11/components/TabBar/components/HomeAction/index.jsx
  themes/theme-ios11/components/TabBar/components/MoreAction/index.jsx
  themes/theme-ios11/components/TabBar/components/TabBarAction/index.jsx
  themes/theme-ios11/components/TabBar/components/actions.js
  themes/theme-ios11/components/TabBar/components/connector.js
  themes/theme-ios11/components/TabBar/helpers/isTabBarVisible.js
  themes/theme-ios11/components/TabBar/helpers/isTabBarVisible.spec.js
  themes/theme-ios11/components/TabBar/helpers/shouldCartHaveTabBar.js
  themes/theme-ios11/components/TabBar/helpers/shouldCartHaveTabBar.spec.js
  themes/theme-ios11/components/TabBar/index.jsx
  themes/theme-ios11/components/TabBar/subscriptions.js
  themes/theme-ios11/components/TabBar/tabs.js
  themes/theme-ios11/components/Viewport/constants.js
  themes/theme-ios11/components/Viewport/index.jsx
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#868 Removed unused setting from gmd extension-config
  themes/theme-gmd/extension-config.json
Labels: internal

#867 Enabled the NavDrawer of the GMD theme for screen readers (a11y)
  libraries/engage/product/components/ProductProperties/__tests__/Content.spec.jsx
  libraries/ui-material/NavDrawer/components/Divider/__snapshots__/spec.jsx.snap
  libraries/ui-material/NavDrawer/components/Divider/index.jsx
  libraries/ui-material/NavDrawer/components/Item/index.jsx
  libraries/ui-material/NavDrawer/components/Item/style.js
  libraries/ui-material/NavDrawer/components/Section/__snapshots__/index.spec.jsx.snap
  libraries/ui-material/NavDrawer/index.jsx
  libraries/ui-material/NavDrawer/spec.jsx
  libraries/ui-material/NavDrawer/transition.js
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-gmd/components/NavDrawer/components/Main/components/CartButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/Main/components/FavoritesButton/components/Badge/connector.js
  themes/theme-gmd/components/NavDrawer/components/Main/components/FavoritesButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/Main/components/ScannerButton/index.jsx
  themes/theme-gmd/components/NavDrawer/components/QuickLinks/index.jsx
  themes/theme-gmd/components/NavDrawer/index.jsx
  themes/theme-gmd/components/Viewport/index.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
Labels: enhancement

#870 Implemented error handling for broken internet connections
  libraries/common/subscriptions/app.js
  libraries/common/subscriptions/error.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
  libraries/core/classes/PipelineManager/index.js
  libraries/core/classes/PipelineManager/spec.js
  libraries/core/constants/Pipeline.js
  libraries/ui-material/SnackBar/index.jsx
  libraries/ui-material/SnackBar/style.js
Labels: enhancement

#871 Fixed onClick handers for custom SearchSuggestionItem components within the iOS 11 theme
  libraries/common/components/Input/components/SimpleInput.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/style.js
Labels: bug
