Repository shopgate/pwa, pull requests merged in 2019-01, with the labels that each got.

#478 Fixed invalid it-IT language file
  package.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  utils/eslint-config/package.json
  utils/eslint-config/ruleset/extras.js
  yarn.lock
Labels: bug, enhancement

#477 Fixed invalid it-IT translation file
  themes/theme-gmd/locale/it-IT.json
Labels: bug

#480 Corrected issue where page scrolling was not consistent
  themes/theme-gmd/components/View/components/Content/index.jsx
  themes/theme-ios11/components/View/components/Content/index.jsx
Labels: bug

#479 Liveshopping widget refactoring
  libraries/ui-shared/DiscountBadge/style.js
  themes/theme-gmd/pages/index.jsx
  themes/theme-gmd/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/components/Discount/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/Liveshopping/components/Discount/index.jsx
  themes/theme-gmd/widgets/Liveshopping/components/Discount/spec.jsx
  themes/theme-gmd/widgets/Liveshopping/components/Discount/style.js
  themes/theme-gmd/widgets/Liveshopping/components/Item/connector.js
  themes/theme-gmd/widgets/Liveshopping/components/Item/helpers.js
  themes/theme-gmd/widgets/Liveshopping/components/Item/index.jsx
  themes/theme-gmd/widgets/Liveshopping/components/Item/style.js
  themes/theme-gmd/widgets/Liveshopping/connector.js
  themes/theme-gmd/widgets/Liveshopping/index.jsx
  themes/theme-gmd/widgets/Liveshopping/selectors.js
  themes/theme-gmd/widgets/Liveshopping/spec.jsx
  themes/theme-gmd/widgets/Liveshopping/style.js
  themes/theme-ios11/widgets/Liveshopping/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Liveshopping/components/Discount/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/Liveshopping/components/Discount/index.jsx
  themes/theme-ios11/widgets/Liveshopping/components/Discount/spec.jsx
  themes/theme-ios11/widgets/Liveshopping/components/Discount/style.js
  themes/theme-ios11/widgets/Liveshopping/components/Item/connector.js
  themes/theme-ios11/widgets/Liveshopping/components/Item/helpers.js
  themes/theme-ios11/widgets/Liveshopping/components/Item/index.jsx
  themes/theme-ios11/widgets/Liveshopping/components/Item/style.js
  themes/theme-ios11/widgets/Liveshopping/connector.js
  themes/theme-ios11/widgets/Liveshopping/index.jsx
  themes/theme-ios11/widgets/Liveshopping/selectors.js
  themes/theme-ios11/widgets/Liveshopping/spec.jsx
  themes/theme-ios11/widgets/Liveshopping/style.js
  yarn.lock
Labels: enhancement

#482 Updated conductor to v2.0.5
  libraries/common/package.json
  themes/theme-gmd/package.json
  themes/theme-ios11/components/FilterBar/index.jsx
  themes/theme-ios11/package.json
  themes/theme-ios11/pages/index.jsx
  yarn.lock
Labels: bug

#481 Improved layout of "no product results" pages with active filters
  libraries/ui-shared/NoResults/style.js
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
Labels: bug

#484 Corrected bug where product reviews were not always requested
  libraries/commerce/reviews/streams/index.js
Labels: bug

#483 Corrected bug where page configs were fetched on every page …
  libraries/common/actions/page/getPageConfig.js
  libraries/common/reducers/page/index.js
  themes/theme-gmd/pages/StartPage/subscriptions.js
  themes/theme-ios11/pages/StartPage/subscriptions.js
Labels: bug

#485 Added Drawer theme component to ThemeContext
  libraries/ui-shared/index.js
  themes/theme-gmd/components/Drawer/index.jsx
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-gmd/pages/index.jsx
  themes/theme-gmd/pages/themeApi.js
  themes/theme-ios11/components/Drawer/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-ios11/pages/index.jsx
  themes/theme-ios11/pages/themeApi.js
Labels: enhancement

#486 Added AppBar portals
  libraries/common/components/index.js
  libraries/common/constants/Portals.js
  themes/theme-gmd/components/AppBar/presets/BackBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/BackBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
Labels: enhancement

#474 Add new actions to manipulate product meta data and fixed Sheet
  libraries/commerce/product/actions/updateMetadata.js
  libraries/commerce/product/constants/index.js
  libraries/commerce/product/reducers/productsById.js
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/selectors/product.spec.js
  libraries/ui-shared/Sheet/index.jsx
Labels: bug, enhancement

#489 PWA 1544: Menu selectors doesn't match the reducer name
  libraries/common/selectors/menu.js
  themes/theme-gmd/components/NavDrawer/components/QuickLinks/connector.js
  themes/theme-gmd/components/NavDrawer/selectors.js
  themes/theme-ios11/pages/More/components/Quicklinks/connector.js
  themes/theme-ios11/pages/More/components/Quicklinks/index.spec.jsx
  themes/theme-ios11/pages/More/components/Quicklinks/selectors.js
  utils/e2e/package.json
  yarn.lock
Labels: bug

#492 Added ProductSlider to the ThemeContext
  libraries/common/components/index.js
  themes/theme-gmd/components/ProductSlider/index.jsx
  themes/theme-gmd/components/ProductSlider/style.js
  themes/theme-gmd/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-gmd/themeApi/index.js
  themes/theme-ios11/components/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductSlider/style.js
  themes/theme-ios11/themeApi/ProductCard/components/Price/index.jsx
  themes/theme-ios11/themeApi/index.js
Labels: enhancement

#493 Re-enabled SubMenu Headers in GMD NavDrawer
  libraries/ui-material/NavDrawer/components/Title/index.jsx
  libraries/ui-material/NavDrawer/components/Title/style.js
  libraries/ui-material/NavDrawer/index.jsx
  themes/theme-gmd/components/NavDrawer/components/StoreInfo/index.jsx
  themes/theme-gmd/components/NavDrawer/components/SubHeader/style.js
  themes/theme-gmd/components/NavDrawer/index.jsx
Labels: enhancement

#495 Added action fallbacks for backwards compatibility to PWA 6.0.0
  libraries/commerce/favorites/actions/fetchFavorites.js
  libraries/commerce/favorites/actions/getFavorites.js
  libraries/commerce/filter/actions/getFilters.js
Labels: bug

#496 Added fallback for renamed getProductPrice selector
  libraries/commerce/product/selectors/product.js
Labels: bug

#497 Fixed metadata addition to addProductsToCart payload
  libraries/commerce/cart/actions/addProductsToCart.js
  libraries/commerce/product/selectors/product.js
Labels: bug

#501 Improved PWA pre-commit hook
  package.json
Labels: enhancement

#491 Wrapped all AppBar presets in the themes with additional portal make it possible to extend it
  libraries/common/constants/Portals.js
  libraries/ui-ios/AppBar/components/Below/index.jsx
  libraries/ui-ios/AppBar/components/Center/index.jsx
  libraries/ui-ios/AppBar/components/Left/index.jsx
  libraries/ui-ios/AppBar/components/Right/index.jsx
  libraries/ui-ios/AppBar/components/Title/style.js
  libraries/ui-ios/AppBar/index.jsx
  libraries/ui-material/AppBar/components/Below/index.jsx
  libraries/ui-material/AppBar/components/Center/index.jsx
  libraries/ui-material/AppBar/components/Left/index.jsx
  libraries/ui-material/AppBar/components/Right/index.jsx
  libraries/ui-material/AppBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/BackBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/CartButton/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/components/ProgressBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-gmd/components/AppBar/presets/SimpleBar/index.jsx
  themes/theme-gmd/pages/Page/components/Content/index.jsx
  themes/theme-ios11/components/AppBar/components/CartButton/index.jsx
  themes/theme-ios11/components/AppBar/presets/BackBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/CloseBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/DefaultBar/index.jsx
  themes/theme-ios11/components/AppBar/presets/SimpleBar/index.jsx
  themes/theme-ios11/pages/Page/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/AppBar/index.jsx
  themes/theme-ios11/theme-config.js
Labels: enhancement

#507 Changed more menu styling and aligned theme ios11 and gmd designs to be more compatible
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Item/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Item/index.jsx
  themes/theme-ios11/pages/More/components/Item/style.js
  themes/theme-ios11/pages/More/components/Quicklinks/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/Section/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/StoreInfo/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/StoreInfo/components/ReturnPolicy/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/components/LoggedIn/index.jsx
  themes/theme-ios11/pages/More/components/UserMenu/index.spec.jsx
  themes/theme-ios11/pages/More/style.js
Labels: enhancement

#508 Add ellipsis for product properties in a cart view
  libraries/ui-shared/ProductProperties/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
Labels: enhancement

#505 Update conductor module to fix history reset
  libraries/common/package.json
  themes/theme-gmd/components/FilterBar/components/Content/components/Sort/index.jsx
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: bug

#498 Sort order param for get highlighted products action is added
  libraries/commerce/product/actions/fetchHighlightProducts.js
Labels: enhancement

#499 Sort order param for get highlighted products action is added
  libraries/commerce/product/actions/getHighlightProducts.js
Labels: enhancement
