Repository shopgate/pwa, pull requests merged in 2019-08, with the labels that each got.

#783 Added missing portals for empty favorites page and empty search results page
  libraries/commerce/favorites/constants/Portals.js
  themes/theme-gmd/pages/Favorites/components/EmptyFavorites/index.jsx
  themes/theme-gmd/pages/Search/components/Content/index.jsx
  themes/theme-ios11/pages/Favorites/components/EmptyFavorites/index.jsx
  themes/theme-ios11/pages/Search/components/Content/index.jsx
Labels: enhancement

#786 Fixed inconsistent spacing from the Browse page of the iOS theme
  themes/theme-ios11/pages/Browse/components/Content/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/Content/index.jsx
  themes/theme-ios11/pages/Browse/components/Content/styles.js
  themes/theme-ios11/pages/Browse/components/RootCategories/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/RootCategories/styles.js
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/style.js
  themes/theme-ios11/pages/Browse/components/SearchField/style.js
Labels: bug

#787 Product Image does not flicker when opening the PDP for the first time.
  libraries/engage/product/components/Media/MediaImage.jsx
  libraries/engage/product/components/ProductImage/__snapshots__/spec.jsx.snap
  libraries/engage/product/components/ProductImage/index.jsx
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
Labels: bug

#788 Added Portals to the Search Suggestions components.
  libraries/commerce/search/constants/Portals.js
  libraries/commerce/search/index.js
  libraries/engage/search/index.js
  themes/theme-gmd/components/Search/components/Suggestions/components/List/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/Search/components/Suggestions/components/List/index.jsx
  themes/theme-gmd/components/Search/components/Suggestions/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/spec.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/spec.jsx
Labels: enhancement

#784 Added supported tracking services to the options for tracking plugins
  libraries/core/helpers/version.js
  libraries/tracking/subscriptions/setup.js
Labels: enhancement

#791 Included additional portal props in the SuggestionList component for both themes.
  themes/theme-gmd/components/Search/components/Suggestions/components/List/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/Search/components/Suggestions/components/List/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
Labels: enhancement

#792 Padding to the bottom of the Product Grid is only added if the Grid is not empty.
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Layout/style.js
Labels: bug

#794 Removed a duplicated case clause in the scanner's reducer switch.
  libraries/commerce/scanner/actions/handleQrCode.js
Labels: polish

#798 Renamed LICENSE file
  LICENSE
Labels: polish

#796 Fixed XOR usage in the object merge helper to output warnings correctly.
  libraries/common/helpers/data/index.js
Labels: bug

#795 Removed unnecessary ternary operators in the changelog generator script.
  scripts/build-changelog.js
Labels: polish

#799 Changed the search component in theme-gmd to use the event's currentTarget propery over the target to obtain the updated query.
  themes/theme-gmd/components/Search/index.jsx
Labels: bug

#806 Improved sanitization for purchase tracking event data
  libraries/tracking-core/helpers/formatHelpers.js
Labels: enhancement

#808 Added the ability to modify the search query when using the search suggestion portals in theme ios.
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
Labels: enhancement

#811 Extended source data for the tracking system
  libraries/common/selectors/router.js
  libraries/common/selectors/router.spec.js
  libraries/engage/page/index.js
  libraries/tracking/helpers/index.js
  libraries/tracking/helpers/index.spec.js
  libraries/tracking/selectors/category.js
  libraries/tracking/selectors/index.js
  libraries/tracking/selectors/page.js
  libraries/tracking/selectors/product.js
  libraries/tracking/streams/page.js
  libraries/tracking/streams/page.spec.js
  libraries/tracking/streams/pages.js
  libraries/tracking/subscriptions/pages.js
  libraries/tracking/subscriptions/product.js
Labels: enhancement

#810 Show stock warnings inside variant selection sheet
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
Labels: bug

#809 Show stock warnings inside variant selection sheet
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
Labels: bug

#812 Implemented logItemview tracking event for the tracking core
  libraries/core/commands/unifiedTracking.js
  libraries/tracking-core/core/AppHandler.js
  libraries/tracking-core/helpers/formatHelpers.js
  libraries/tracking/subscriptions/setup.js
Labels: enhancement

#813 Updated dependencies of @shopgate/tracking-ga-native package
  extensions/@shopgate-tracking-ga-native/frontend/package.json
Labels: internal

#814 Fixed the JSDoc type annotations
  libraries/common/helpers/config/index.js
Labels: polish

#817 The SuggestionList component is now persistent in the component tree
  themes/theme-gmd/components/Search/components/Suggestions/components/List/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/components/Search/components/Suggestions/components/List/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/components/SuggestionList/style.js
  themes/theme-ios11/pages/Browse/components/SearchField/index.jsx
  themes/theme-ios11/pages/Browse/components/SearchField/spec.jsx
Labels: bug

#819 Implemented login tracking event for apps
  libraries/common/action-creators/user/index.js
  libraries/common/action-creators/user/spec.js
  libraries/common/actions/user/login.js
  libraries/common/constants/user.js
  libraries/common/reducers/user/login.js
  libraries/core/commands/unifiedTracking.js
  libraries/engage/user/index.js
  libraries/engage/user/selectors/__tests__/login.spec.js
  libraries/engage/user/selectors/login.js
  libraries/tracking-core/core/AppHandler.js
  libraries/tracking-core/helpers/formatHelpers.js
  libraries/tracking-core/helpers/formatHelpers.spec.js
  libraries/tracking/selectors/user.js
  libraries/tracking/selectors/user.spec.js
  libraries/tracking/streams/user.js
  libraries/tracking/streams/user.spec.js
  libraries/tracking/subscriptions/user.js
  libraries/tracking/subscriptions/user.spec.js
Labels: enhancement

#820 Extract discount amount from tracked event initiatedCheckout.
  libraries/commerce/cart/selectors/index.js
  libraries/commerce/cart/selectors/spec.js
  libraries/commerce/product/reducers/resultsByHash.js
  libraries/tracking/selectors/cart.js
  libraries/tracking/selectors/cart.spec.js
  utils/eslint-config/ruleset/main.js
Labels: bug
