Repository shopgate/pwa, pull requests merged in 2020-01, with the labels that each got.

#885 Speeded up the e2e test suite execution for the GMD theme
  libraries/common/streams/main.js
  themes/theme-gmd/e2e/elements/de.js
  themes/theme-gmd/e2e/helper/cart.js
  themes/theme-gmd/e2e/helper/category.js
  themes/theme-gmd/e2e/helper/navigation.js
  themes/theme-gmd/e2e/helper/user.js
  themes/theme-gmd/e2e/integration/consistency/CartPage.js
  themes/theme-gmd/e2e/integration/consistency/CartPageCoupon.js
  themes/theme-gmd/e2e/integration/consistency/CategoryPage.js
  themes/theme-gmd/e2e/integration/consistency/FavoritesPage.js
  themes/theme-gmd/e2e/integration/consistency/FilterPage.js
  themes/theme-gmd/e2e/integration/consistency/LoginPage.js
  themes/theme-gmd/e2e/integration/consistency/NavDrawer.js
  themes/theme-gmd/e2e/integration/consistency/ProductPage.js
  themes/theme-gmd/e2e/integration/consistency/ReviewsPage.js
  themes/theme-gmd/e2e/integration/consistency/SearchPage.js
  themes/theme-gmd/e2e/integration/consistency/StartPage.js
  themes/theme-gmd/e2e/integration/functional/CartPage.js
  themes/theme-gmd/e2e/integration/functional/CartPageCoupon.js
  themes/theme-gmd/e2e/integration/functional/CartPageOptions.js
  themes/theme-gmd/e2e/integration/functional/CategoryPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPage.js
  themes/theme-gmd/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-gmd/e2e/integration/functional/FilterPage.js
  themes/theme-gmd/e2e/integration/functional/LoginPage.js
  themes/theme-gmd/e2e/integration/functional/ProductPage.js
  themes/theme-gmd/e2e/integration/functional/ProductPageOptions.js
  themes/theme-gmd/e2e/integration/functional/SearchPage.js
  themes/theme-gmd/e2e/integration/functional/StartPage.js
  themes/theme-gmd/e2e/integration/specFiles/consistency/legacy.js
  themes/theme-gmd/e2e/integration/specFiles/functional/legacy.js
  utils/e2e/plugins/index.js
  utils/e2e/support/commands.js
  utils/e2e/support/index.js
Labels: internal

#886 Speeded up the e2e test suite execution for the iOS 11 theme
  themes/theme-ios11/e2e/cypress.json
  themes/theme-ios11/e2e/elements/de.js
  themes/theme-ios11/e2e/helper/cart.js
  themes/theme-ios11/e2e/helper/category.js
  themes/theme-ios11/e2e/helper/coupon.js
  themes/theme-ios11/e2e/helper/form.js
  themes/theme-ios11/e2e/helper/navigation.js
  themes/theme-ios11/e2e/helper/user.js
  themes/theme-ios11/e2e/integration/consistency/CartPage.js
  themes/theme-ios11/e2e/integration/consistency/CartPageCoupon.js
  themes/theme-ios11/e2e/integration/consistency/CategoryPage.js
  themes/theme-ios11/e2e/integration/consistency/FavoritesPage.js
  themes/theme-ios11/e2e/integration/consistency/FilterPage.js
  themes/theme-ios11/e2e/integration/consistency/LoginPage.js
  themes/theme-ios11/e2e/integration/consistency/ProductPage.js
  themes/theme-ios11/e2e/integration/consistency/ProductPageOption.js
  themes/theme-ios11/e2e/integration/consistency/ReviewsPage.js
  themes/theme-ios11/e2e/integration/consistency/SearchPage.js
  themes/theme-ios11/e2e/integration/consistency/StartPage.js
  themes/theme-ios11/e2e/integration/functional/CartPage.js
  themes/theme-ios11/e2e/integration/functional/CartPageCoupons.js
  themes/theme-ios11/e2e/integration/functional/CartPageOptions.js
  themes/theme-ios11/e2e/integration/functional/CategoryPage.js
  themes/theme-ios11/e2e/integration/functional/FavoritesPage.js
  themes/theme-ios11/e2e/integration/functional/FavoritesPageOptions.js
  themes/theme-ios11/e2e/integration/functional/FilterPage.js
  themes/theme-ios11/e2e/integration/functional/LoginPage.js
  themes/theme-ios11/e2e/integration/functional/MorePage.js
  themes/theme-ios11/e2e/integration/functional/ProductPage.js
  themes/theme-ios11/e2e/integration/functional/ProductPageOptions.js
  themes/theme-ios11/e2e/integration/functional/SearchPage.js
  themes/theme-ios11/e2e/integration/functional/StartPage.js
  themes/theme-ios11/e2e/integration/specFiles/consistency/legacy.js
  themes/theme-ios11/e2e/integration/specFiles/functional/legacy.js
Labels: internal

#894 Introduced new app setting to configure a individual locale for price formatting
  libraries/engage/core/helpers/__tests__/i18n.spec.js
  libraries/engage/core/helpers/i18n.js
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/index.jsx
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/index.jsx
Labels: enhancement

#895 Fixed issues with long cached and wrong checkout related urls
  libraries/common/reducers/url/index.js
  libraries/common/store/index.js
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/common/subscriptions/helpers/handleLinks.spec.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
Labels: bug

#896 Fixed a react package version incompatibility
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
Labels: bug

#901 Update routes portals collection when extension config, containing routes, is changed
  libraries/common/helpers/portals/__tests__/routePortals.js
  libraries/common/helpers/portals/routePortals.js
Labels: bug

#904 Fixed sort filter entries text color
  themes/theme-gmd/components/FilterBar/components/Content/components/Sort/style.js
  themes/theme-ios11/components/FilterBar/components/Content/components/Sort/style.js
Labels: bug
