Repository shopgate/pwa, pull requests merged in 2020-03, with the labels that each got.

#947 Store operation hours are sorted wrong
  libraries/engage/core/__mocks__/index.js
  libraries/engage/core/helpers/__mocks__/i18n.js
  libraries/engage/core/helpers/__tests__/i18n.spec.js
  libraries/engage/core/helpers/i18n.js
  libraries/engage/core/index.js
  libraries/engage/core/index.spec.js
  libraries/engage/locations/components/StoreList/StoreAddressOpeningHours.jsx
  libraries/engage/locations/components/StoreList/StoreAddressOpeningHoursLine.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddressOpeningHours.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressOpeningHours.spec.jsx.snap
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: internal

#949 Added disabled state for add to cart button when ROPE products are not orderable
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.types.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorAddToCart.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorAddToCart.jsx
  libraries/engage/locations/index.js
  libraries/engage/locations/locations.types.js
  libraries/engage/locations/selectors/__tests__/index.spec.js
  libraries/engage/locations/selectors/index.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
Labels: enhancement

#950 Cart reservation groups now show the store name instead of its address
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.jsx
Labels: enhancement

#951 Improved display of distances to the store locations
  libraries/engage/locations/components/StoreList/StoreAddressDistance.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddressDistance.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressDistance.spec.jsx.snap
  libraries/engage/locations/helpers/__tests__/formatDistance.spec.js
  libraries/engage/locations/helpers/formatDistance.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#948 Variant availability and error messages
  libraries/engage/a11y/__mocks__/index.js
  libraries/engage/locations/__mocks__/index.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.style.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorItem.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorItemDirectShip.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorItemDirectShip.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorItemReserve.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/FulfillmentSelector.spec.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/__snapshots__/FulfillmentSelector.spec.jsx.snap
  libraries/engage/locations/components/StockInfo/StockInfo.defaultSettings.js
  libraries/engage/locations/helpers/getAvailabilitySettings.js
  libraries/engage/locations/selectors/__tests__/index.spec.js
  libraries/engage/locations/selectors/index.js
  libraries/engage/product/__mocks__/index.js
  libraries/engage/product/components/ProductVariants/VariantAvailability.connector.js
  libraries/engage/product/components/ProductVariants/VariantAvailability.jsx
  libraries/engage/product/components/ProductVariants/VariantAvailability.style.js
  libraries/engage/product/components/ProductVariants/index.js
  libraries/engage/product/components/context.js
  libraries/engage/product/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/connector.js
  themes/theme-gmd/pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/index.jsx
  themes/theme-gmd/pages/Product/components/Content/connector.js
  themes/theme-gmd/pages/Product/components/Content/index.jsx
  themes/theme-gmd/pages/Product/components/Content/spec.jsx
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/index.jsx
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-gmd/pages/Product/context.js
  themes/theme-gmd/themeApi/index.js
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/connector.js
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/index.jsx
  themes/theme-ios11/pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/style.js
  themes/theme-ios11/pages/Product/components/Content/connector.js
  themes/theme-ios11/pages/Product/components/Content/index.jsx
  themes/theme-ios11/pages/Product/components/Content/spec.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/pages/Product/context.js
  themes/theme-ios11/themeApi/index.js
Labels: internal

#952 Prefill reservation form with logged in user data
  libraries/engage/locations/selectors/__tests__/index.spec.js
  libraries/engage/locations/selectors/index.js
Labels: internal

#954 Removed duplicate headline in reserve sheet
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: polish

#953 Added google maps url to fulfillment location sheet
  libraries/common/components/Link/index.jsx
  libraries/common/subscriptions/helpers/handleLinks.js
  libraries/common/subscriptions/router.js
  libraries/common/subscriptions/router.spec.js
  libraries/engage/core/helpers/__tests__/googleMaps.spec.js
  libraries/engage/core/helpers/googleMaps.js
  libraries/engage/core/index.js
  libraries/engage/locations/components/StoreList/StoreAddressMailingAddress.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressDistance.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressHeading.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressHoursToday.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressMailingAddress.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressOpeningHours.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressPhoneNumber.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressStoreDetails.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListProduct.spec.jsx.snap
  libraries/engage/locations/components/StoreList/style.js
  themes/theme-gmd/components/Reviews/components/Header/__snapshots__/spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/Reviews/components/Header/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Browse/components/RootCategories/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/components/UserMenu/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/themeApi/ProductCard/components/Render/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: enhancement

#955 Show static header if no Store information is given
  libraries/engage/cart/components/CartItems/CartItemGroup.style.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.connector.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.jsx
  libraries/engage/cart/components/CartItems/CartItemGroupReservationLabel.jsx
  libraries/engage/cart/components/CartItems/__tests__/CartItemGroupReservation.spec.jsx
  libraries/engage/cart/components/CartItems/__tests__/__snapshots__/CartItemGroupReservation.spec.jsx.snap
  libraries/engage/components/__mocks__/index.js
  libraries/engage/locations/__mocks__/index.js
Labels: internal

#957 Exchange update cart pipeline
  libraries/commerce/cart/actions/updateProductsInCart.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.connector.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.jsx
  libraries/engage/cart/components/CartItems/CartItemGroupReservationLabel.jsx
  libraries/engage/cart/components/CartItems/__tests__/__snapshots__/CartItemGroupReservation.spec.jsx.snap
  libraries/engage/locations/constants/Pipelines.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/locations.types.js
  libraries/engage/locations/subscriptions.js
Labels: internal

#959 Show Fulfillment Selector disabled if the product doesn't have ROPIS enabled, but the shop has.
  libraries/engage/core/config/config.selectors.js
  libraries/engage/core/config/index.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.types.js
  libraries/engage/locations/components/FulfillmentSelector/__tests__/FulfillmentSelector.spec.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/__snapshots__/FulfillmentSelector.spec.jsx.snap
  libraries/engage/locations/selectors/index.js
Labels: internal

#958 Product locations are always refreshed, once the user opens the fulfillment sheet.
  libraries/engage/locations/action-creators/index.js
  libraries/engage/locations/action-creators/storeSearchQuery.js
  libraries/engage/locations/components/StoreList/StoreListSearch.connector.js
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListSearch.spec.jsx.snap
  libraries/engage/locations/constants/ActionTypes.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/locations.types.js
  libraries/engage/locations/reducers/index.js
  libraries/engage/locations/reducers/userSearchQuery.js
  libraries/engage/locations/selectors/index.js
Labels: internal

#961 On choosing "Someone else" the form should scroll up
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
Labels: internal

#963 Add missing gap.xsmall to ios theme. Refactor cart group reservation
  libraries/engage/cart/components/CartItems/CartItemGroup.style.js
  libraries/engage/locations/components/Cart/CartItemProductChangeLocation.jsx
  themes/theme-ios11/theme-config.js
Labels: internal

#962 Fulfillment locations header style
  libraries/engage/components/MessageBar/MessageBar.jsx
  libraries/engage/components/MessageBar/MessageBar.style.js
  libraries/engage/components/MessageBar/MessageBar.types.js
  libraries/engage/components/MessageBar/__tests__/MessageBar.spec.jsx
  libraries/engage/components/MessageBar/__tests__/__snapshots__/MessageBar.spec.jsx.snap
  libraries/engage/components/MessageBar/index.js
  libraries/engage/components/MessageBar/style.js
  libraries/engage/components/index.js
  libraries/engage/locations/components/FulfillmentSheet/FulfillmentSheet.connector.js
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  libraries/engage/locations/components/StoreList/StoreListProduct.jsx
  libraries/engage/locations/components/StoreList/StoreListProduct.style.js
  libraries/engage/locations/components/StoreList/StoreListProductInfo.jsx
  libraries/engage/locations/components/StoreList/StoreListProductName.jsx
  libraries/engage/locations/components/StoreList/StoreListProductVariants.connector.js
  libraries/engage/locations/components/StoreList/StoreListProductVariants.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.style.js
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListProduct.spec.jsx.snap
  libraries/engage/locations/components/StoreList/style.js
  libraries/engage/locations/locations.context.js
  libraries/engage/locations/providers/FulfillmentProvider.connector.js
  libraries/engage/locations/providers/FulfillmentProvider.jsx
  libraries/engage/locations/providers/FulfillmentProvider.types.js
  libraries/engage/product/index.js
  libraries/engage/product/product.types.js
  libraries/ui-shared/icons/InfoIcon.jsx
Labels: internal

#964 Fixed Form Builder element visibility
  libraries/engage/components/Form/Builder/Builder.jsx
  libraries/engage/components/Form/Builder/Builder.spec.jsx
  libraries/engage/components/Form/Builder/ElementCheckbox.jsx
  libraries/engage/components/Form/Builder/ElementRadio.jsx
  libraries/engage/components/Form/Builder/ElementSelect.jsx
  libraries/engage/components/Form/Builder/ElementText.jsx
  libraries/engage/components/Form/Builder/__snapshots__/Builder.spec.jsx.snap
Labels: bug

#967 Change fulfillment method in Mixed cart
  libraries/core/helpers/index.js
  libraries/engage/locations/components/FulfillmentPath/FulfillmentPath.jsx
  libraries/engage/locations/components/StoreList/StoreListProduct.style.js
  libraries/engage/locations/components/StoreList/StoreListProductInfo.jsx
  libraries/engage/locations/locations.context.js
  libraries/engage/locations/providers/FulfillmentProvider.connector.js
  libraries/engage/locations/providers/FulfillmentProvider.jsx
  libraries/engage/locations/providers/FulfillmentProvider.types.js
  libraries/ui-shared/Form/RadioGroup/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/RadioGroup/components/Item/index.jsx
  libraries/ui-shared/Form/RadioGroup/components/Item/style.js
Labels: internal

#968 Removed semi-automated and incorrect validation error handling in the From Builder.
  libraries/engage/components/Form/Builder/Builder.jsx
  libraries/engage/components/Form/Builder/Builder.spec.jsx
  libraries/engage/components/Form/Builder/__snapshots__/Builder.spec.jsx.snap
Labels: bug

#972 User gets thrown back to homepage if ropis checkout is cancelled
  libraries/engage/locations/providers/FulfillmentProvider.jsx
Labels: internal

#971 Cart update of ropis item
  libraries/engage/locations/providers/FulfillmentProvider.jsx
Labels: internal

#973 Fix cart item messages with custom styles
  libraries/engage/components/MessageBar/__snapshots__/spec.jsx.snap
  libraries/engage/components/MessageBar/index.jsx
  libraries/engage/components/MessageBar/spec.jsx
  libraries/engage/components/MessageBar/style.js
  libraries/ui-shared/MessageBar/__snapshots__/spec.jsx.snap
  libraries/ui-shared/MessageBar/index.jsx
  libraries/ui-shared/MessageBar/spec.jsx
  libraries/ui-shared/MessageBar/style.js
Labels: bug

#970 Country selector for zipcode search
  libraries/engage/components/__mocks__/index.js
  libraries/engage/core/config/config.selectors.js
  libraries/engage/core/config/config.types.js
  libraries/engage/core/config/index.js
  libraries/engage/core/helpers/i18n.js
  libraries/engage/i18n/__mocks__/countries.hooks.js
  libraries/engage/i18n/countries.hooks.js
  libraries/engage/i18n/locale/de-de/countries.json
  libraries/engage/i18n/locale/en-us/countries.json
  libraries/engage/i18n/locale/es-es/countries.json
  libraries/engage/i18n/locale/fr-fr/countries.json
  libraries/engage/i18n/locale/it-it/countries.json
  libraries/engage/i18n/locale/nl-nl/countries.json
  libraries/engage/i18n/locale/pt-pt/countries.json
  libraries/engage/locations/action-creators/index.js
  libraries/engage/locations/action-creators/storeSearch.js
  libraries/engage/locations/action-creators/storeSearchQuery.js
  libraries/engage/locations/actions/fetchProductLocations.js
  libraries/engage/locations/components/StoreList/StoreListSearch.actions.js
  libraries/engage/locations/components/StoreList/StoreListSearch.connector.js
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.style.js
  libraries/engage/locations/components/StoreList/__tests__/StoreListProduct.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.actions.spec.js
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreDetails.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListSearch.spec.jsx.snap
  libraries/engage/locations/constants/ActionTypes.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/locations.context.js
  libraries/engage/locations/providers/FulfillmentProvider.connector.js
  libraries/engage/locations/providers/FulfillmentProvider.jsx
  libraries/engage/locations/providers/FulfillmentProvider.types.js
  libraries/engage/locations/reducers/index.js
  libraries/engage/locations/reducers/userSearch.js
  libraries/engage/locations/reducers/userSearchQuery.js
  libraries/engage/locations/selectors/index.js
  themes/theme-gmd/locale/index.js
  themes/theme-ios11/locale/index.js
Labels: internal

#974 Improve shouldFetchData redux helper
  libraries/common/helpers/redux/__tests__/shouldFetchData.spec.js
  libraries/common/helpers/redux/shouldFetchData.js
Labels: bug

#975 Improve shouldFetchData redux helper
  libraries/common/helpers/redux/__tests__/shouldFetchData.spec.js
  libraries/common/helpers/redux/shouldFetchData.js
Labels: bug

#976 Direct ship items can not be added to cart
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorAddToCart.jsx
Labels: internal

#978 Validation in reservation form is not correct
  libraries/engage/core/hooks/useFormState.js
  libraries/engage/locations/components/ReserveForm/ReserveForm.constraints.js
Labels: internal

#981 Reservation device info
  libraries/commerce/product/mock.js
  libraries/common/helpers/config/__mocks__/index.js
  libraries/core/helpers/version.js
  libraries/engage/cart/__mocks__/index.js
  libraries/engage/core/__mocks__/index.js
  libraries/engage/core/config/__mocks__/config.selectors.js
  libraries/engage/locations/helpers/__tests__/__snapshots__/createOrder.spec.js.snap
  libraries/engage/locations/helpers/__tests__/createOrder.spec.js
  libraries/engage/locations/helpers/createOrder.js
  libraries/engage/product/__mocks__/index.js
Labels: internal

#977 Compliance of reservation order schema
  libraries/engage/core/helpers/__mocks__/i18n.js
  libraries/engage/core/helpers/i18n.js
  libraries/engage/locations/helpers/createOrder.js
Labels: internal

#980 Wrong availability text in location selector sheet
  libraries/engage/locations/components/StockInfo/StockInfo.defaultSettings.js
  libraries/engage/locations/components/StockInfo/__tests__/__snapshots__/StockInfo.spec.jsx.snap
  libraries/engage/locations/helpers/getAvailabilitySettings.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: internal

#983 FIXED: The FavoritesList items now show the base price.
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/style.js
  themes/theme-gmd/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/style.js
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/index.jsx
  themes/theme-ios11/pages/Favorites/components/FavoritesList/components/Item/components/ProductInfo/components/Price/style.js
Labels: bug

#985 Copy non parsed by babel library files
  Makefile
Labels: bug

#984 Changing variant or loading product does not show unavailable error message anymore.
  libraries/commerce/product/actions/fetchProduct.js
  libraries/commerce/product/subscriptions/index.js
  libraries/commerce/product/subscriptions/index.spec.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorImpossibleError.jsx
Labels: internal

#979 Submit reservation button not activated once clicked
  libraries/engage/core/hooks/__tests__/useFormState.spec.jsx
  libraries/engage/core/hooks/useFormState.js
  libraries/engage/locations/actions/submitReservation.js
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  libraries/engage/locations/components/ReserveForm/ReserveForm.style.js
  libraries/engage/locations/providers/FulfillmentProvider.jsx
  libraries/engage/locations/subscriptions.js
  libraries/ui-shared/Form/Password/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/RadioGroup/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/RadioGroup/index.jsx
  libraries/ui-shared/Form/RadioGroup/style.js
  libraries/ui-shared/Form/Select/__snapshots__/spec.jsx.snap
  libraries/ui-shared/Form/TextField/__snapshots__/spec.jsx.snap
  libraries/ui-shared/FormElement/__snapshots__/spec.jsx.snap
  libraries/ui-shared/FormElement/index.jsx
  libraries/ui-shared/FormElement/style.js
Labels: internal

#986 Keep fulfillment method on pdp
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorReserve.jsx
Labels: internal

#987 Hide reservation availability
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.types.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorDirectShip.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorReserve.jsx
Labels: internal

#989 Add contextTypes back to functional components
  libraries/engage/cart/components/CartItem/CartItemCouponLayout.jsx
  libraries/engage/cart/components/CartItem/CartItemProductLayout.jsx
  libraries/engage/cart/components/CartItem/CartItemProductPrice.jsx
  libraries/engage/cart/components/CartItem/CartItemProductTitle.jsx
Labels: internal

#982 Added country code selector to the Reservation Form phone number field
  libraries/engage/cart/index.js
  libraries/engage/core/hooks/useFormState.js
  libraries/engage/i18n/countries.hooks.js
  libraries/engage/i18n/index.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  libraries/engage/locations/components/ReserveForm/ReserveForm.style.js
  libraries/engage/locations/components/ReserveForm/ReserveFormPhone.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/locations.context.js
  libraries/engage/locations/locations.types.js
  libraries/engage/locations/providers/FulfillmentProvider.jsx
  libraries/engage/locations/providers/FulfillmentProvider.types.js
  libraries/engage/package.json
  yarn.lock
Labels: internal

#990 PWA-2540 Rename PropTypes
  libraries/engage/cart/components/CartItem/CartItemCouponLayout.jsx
  libraries/engage/cart/components/CartItem/CartItemProductLayout.jsx
  libraries/engage/cart/components/CartItem/CartItemProductPrice.jsx
  libraries/engage/cart/components/CartItem/CartItemProductTitle.jsx
Labels: internal

#988 Refined the StoreListSearch component
  libraries/core/classes/AppPermissionsRequest/AppPermissionsRequest.js
  libraries/core/classes/AppPermissionsRequest/GetAppPermissionsRequest.js
  libraries/core/classes/AppPermissionsRequest/GetAppPermissionsRequest.spec.js
  libraries/core/classes/AppPermissionsRequest/RequestAppPermissionsRequest.js
  libraries/core/classes/AppPermissionsRequest/RequestAppPermissionsRequest.spec.js
  libraries/core/classes/AppPermissionsRequest/helpers/createMockedPermissions.js
  libraries/core/classes/AppPermissionsRequest/helpers/createMockedPermissions.spec.js
  libraries/core/classes/Event/index.js
  libraries/core/constants/AppCommands.js
  libraries/core/constants/AppEvents.js
  libraries/engage/components/MessageBar/MessageBar.types.js
  libraries/engage/core/actions/__tests__/grantGeolocationPermissions.spec.js
  libraries/engage/core/actions/grantGeolocationPermissions.js
  libraries/engage/locations/action-creators/__mocks__/index.js
  libraries/engage/locations/action-creators/__tests__/errorLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/errorProductLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/index.spec.js
  libraries/engage/locations/action-creators/__tests__/receiveLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/receiveProductLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/requestLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/requestProductLocations.spec.js
  libraries/engage/locations/action-creators/__tests__/setUserSearchCountryCode.spec.js
  libraries/engage/locations/action-creators/__tests__/setUserSearchPostalCode.spec.js
  libraries/engage/locations/action-creators/__tests__/submitReservationError.spec.js
  libraries/engage/locations/action-creators/__tests__/submitReservationRequest.spec.js
  libraries/engage/locations/action-creators/__tests__/submitReservationSuccess.spec.js
  libraries/engage/locations/action-creators/index.js
  libraries/engage/locations/action-creators/setUserSearchCountryCode.js
  libraries/engage/locations/action-creators/setUserSearchPostalCode.js
  libraries/engage/locations/action-creators/storeSearch.js
  libraries/engage/locations/components/StoreList/StoreListSearch.actions.js
  libraries/engage/locations/components/StoreList/StoreListSearch.connector.js
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.style.js
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.actions.spec.js
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListSearch.spec.jsx.snap
  libraries/engage/locations/constants/ActionTypes.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/index.js
  libraries/engage/locations/providers/FulfillmentProvider.types.js
  libraries/engage/locations/reducers/__tests__/locationsById.spec.js
  libraries/engage/locations/reducers/__tests__/userSearch.spec.js
  libraries/engage/locations/reducers/userSearch.js
  libraries/engage/locations/selectors/__tests__/index.spec.js
  libraries/engage/locations/selectors/index.js
Labels: enhancement

#991 Polish MessageBar
  libraries/engage/cart/components/CartItem/CartItem.style.js
  libraries/engage/components/MessageBar/MessageBar.jsx
  libraries/engage/components/MessageBar/MessageBar.style.js
  libraries/engage/components/MessageBar/MessageBar.types.js
  libraries/engage/components/MessageBar/__tests__/__snapshots__/MessageBar.spec.jsx.snap
  libraries/engage/components/MessageBar/index.jsx
  libraries/engage/locations/components/StoreList/StoreListSearch.style.js
Labels: internal

#993 Change text if product is out of stock in selected store
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorReserve.jsx
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: internal

#992 Fix ready state to hide/show details
  libraries/commerce/product/selectors/product.js
  libraries/commerce/product/selectors/product.spec.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.context.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.types.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorReserve.jsx
Labels: internal

#994 Geolocations are now determined via the getLocation app command api when running in app context
  libraries/engage/core/actions/__tests__/getGeolocation.spec.js
  libraries/engage/core/actions/getGeolocation.js
  libraries/engage/core/classes/GeolocationRequest.js
  libraries/engage/core/classes/GeolocationRequestApp.js
  libraries/engage/core/classes/GeolocationRequestBrowser.js
  libraries/engage/core/classes/__tests__/GeolocationRequest.spec.js
  libraries/engage/core/classes/__tests__/GeolocationRequestApp.spec.js
  libraries/engage/core/classes/__tests__/GeolocationRequestBrowser.spec.js
  libraries/engage/core/constants/geolocationRequest.js
Labels: internal
