Repository shopgate/pwa, pull requests merged in 2020-06, with the labels that each got.

#1012 Make iOS tabbar labels visibility configurable
  libraries/engage/core/hooks/useWidgetSettings.js
  themes/theme-ios11/components/TabBar/components/TabBarAction/index.jsx
  themes/theme-ios11/extension-config.json
Labels: enhancement

#1013 AddToCart button from ui-shared checks for success before show checkmark
  libraries/ui-shared/AddToCartButton/index.jsx
  libraries/ui-shared/AddToCartButton/spec.jsx
Labels: enhancement

#1014 Set correct image for pdp background
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/connector.js
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/connector.js
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/index.jsx
Labels: bug

#1015 Add more details for intersected elements by intersection visibility component
  libraries/engage/components/IntersectionVisibility/__tests__/index.jsx
  libraries/engage/components/IntersectionVisibility/index.jsx
Labels: enhancement

#1017 Change order of content on "Mehr" page of ios theme
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/index.jsx
Labels: polish

#1016 Change order of content on "Mehr" page of ios theme
  themes/theme-ios11/pages/More/__snapshots__/index.spec.jsx.snap
  themes/theme-ios11/pages/More/index.jsx
Labels: polish
