Repository shopgate/pwa, pull requests merged in 2020-04, with the labels that each got.

#996 Fixed pre-selection of the reserve form country
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  libraries/engage/locations/components/ReserveForm/ReserveFormPhone.connector.js
  libraries/engage/locations/components/ReserveForm/ReserveFormPhone.jsx
  libraries/engage/locations/components/ReserveForm/ReserveFormPhone.types.js
  libraries/engage/locations/locations.streams.js
  libraries/engage/locations/selectors/index.js
  libraries/engage/locations/subscriptions.js
Labels: internal

#1002 Fix products grid card dimensions
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Iterator/style.js
  themes/theme-gmd/components/ProductGrid/components/Layout/style.js
  themes/theme-gmd/components/ProductGrid/spec.jsx
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
  themes/theme-ios11/components/ProductGrid/spec.jsx
Labels: bug

#1004 Fix products grid card dimensions
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Iterator/style.js
  themes/theme-gmd/components/ProductGrid/components/Layout/style.js
  themes/theme-gmd/components/ProductGrid/spec.jsx
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
  themes/theme-ios11/components/ProductGrid/spec.jsx
Labels: bug

#1006 Use css grid for themes Product Grid
  libraries/common/components/InfiniteContainer/index.jsx
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Iterator/style.js
  themes/theme-gmd/components/ProductGrid/components/Layout/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Layout/style.js
  themes/theme-gmd/components/ProductGrid/index.jsx
  themes/theme-gmd/components/ProductGrid/spec.jsx
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/components/Layout/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
  themes/theme-ios11/components/ProductGrid/index.jsx
  themes/theme-ios11/components/ProductGrid/spec.jsx
Labels: bug

#1007 Use css grid for themes Product Grid with multiple columns
  libraries/common/components/InfiniteContainer/index.jsx
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Iterator/style.js
  themes/theme-gmd/components/ProductGrid/components/Layout/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Layout/style.js
  themes/theme-gmd/components/ProductGrid/index.jsx
  themes/theme-gmd/components/ProductGrid/spec.jsx
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/components/Layout/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Layout/style.js
  themes/theme-ios11/components/ProductGrid/index.jsx
  themes/theme-ios11/components/ProductGrid/spec.jsx
Labels: enhancement
