Repository shopgate/pwa, pull requests merged in 2020-02, with the labels that each got.

#906 Implemented auto logout after account deletion was requested
  extensions/@shopgate-user-privacy/frontend/DeleteAccount/action.js
  extensions/@shopgate-user-privacy/frontend/DeleteAccount/connector.js
  extensions/@shopgate-user-privacy/frontend/DeleteAccount/subscribers.js
  extensions/@shopgate-user-privacy/frontend/locale/de-DE.json
  extensions/@shopgate-user-privacy/frontend/locale/en-US.json
  extensions/@shopgate-user-privacy/frontend/locale/es-ES.json
  extensions/@shopgate-user-privacy/frontend/locale/fr-FR.json
  extensions/@shopgate-user-privacy/frontend/locale/it-IT.json
  extensions/@shopgate-user-privacy/frontend/locale/nl-NL.json
  extensions/@shopgate-user-privacy/frontend/locale/pt-PT.json
  libraries/common/action-creators/user/index.js
  libraries/common/action-creators/user/spec.js
  libraries/common/actions/user/logout.js
  libraries/common/subscriptions/user.js
Labels: enhancement

#912 Export mutable actions as a part of engage api
  libraries/common/helpers/redux/index.js
  libraries/common/helpers/redux/mutable.js
Labels: enhancement

#911 Some unused selectors have been removed or deprecated.
  libraries/commerce/product/selectors/page.js
  libraries/commerce/product/selectors/page.spec.js
  libraries/core/helpers/index.js
  themes/theme-gmd/components/FilterBar/components/Content/selectors.js
  themes/theme-ios11/components/FilterBar/components/Content/selectors.js
Labels: polish

#913 Added missing portals to root category page of gmd theme
  libraries/common/helpers/config/__mocks__/index.js
  libraries/engage/components/__mocks__/index.js
  themes/theme-gmd/components/AppBar/presets/__mocks__/index.js
  themes/theme-gmd/pages/Category/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/Category/spec.jsx
  themes/theme-gmd/pages/RootCategory/__snapshots__/spec.jsx.snap
  themes/theme-gmd/pages/RootCategory/index.jsx
  themes/theme-gmd/pages/RootCategory/spec.jsx
  themes/theme-gmd/pages/RootCategory/subscriptions/spec.js
  themes/theme-ios11/pages/Category/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/Category/spec.jsx
Labels: enhancement

#914 Fixed duplication of new array config entries on reference resolving. Further improved the config resolve algorithm to also support concatenated configs using references and custom text.
  libraries/common/helpers/config/index.js
  libraries/engage/core/config/ThemeConfigResolver.js
Labels: bug

#917 Fixed broken image sliders on Chrome > 80
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#918 Fixed broken image sliders on Chrome > 80
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#919 Fixed broken image sliders on Chrome > 80
  libraries/common/components/Swiper/styles.js
  themes/theme-gmd/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-gmd/widgets/ImageSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/pages/ProductGallery/components/Content/components/ImagesSlider/__snapshots__/spec.jsx.snap
  themes/theme-ios11/widgets/ImageSlider/__snapshots__/spec.jsx.snap
Labels: bug

#920 Removed error logs from pipeline request actions
  libraries/commerce/cart/actions/addCouponsToCart.js
  libraries/commerce/cart/actions/addProductsToCart.js
  libraries/commerce/cart/actions/deleteCouponsFromCart.js
  libraries/commerce/cart/actions/deleteProductsFromCart.js
  libraries/commerce/cart/actions/fetchCart.js
  libraries/commerce/cart/actions/updateProductsInCart.js
  libraries/commerce/category/actions/fetchCategory.js
  libraries/commerce/category/actions/fetchCategoryChildren.js
  libraries/commerce/category/actions/fetchRootCategories.js
  libraries/commerce/checkout/actions/fetchCheckoutUrl.js
  libraries/commerce/checkout/actions/fetchCheckoutUrl.spec.js
  libraries/commerce/favorites/actions/addFavorites.js
  libraries/commerce/favorites/actions/addFavorites.spec.js
  libraries/commerce/favorites/actions/fetchFavorites.js
  libraries/commerce/favorites/actions/removeFavorites.js
  libraries/commerce/favorites/actions/removeFavorites.spec.js
  libraries/commerce/filter/actions/fetchFilters.js
  libraries/commerce/product/actions/fetchProduct.js
  libraries/commerce/product/actions/fetchProductDescription.js
  libraries/commerce/product/actions/fetchProductImages.js
  libraries/commerce/product/actions/fetchProductMedia.js
  libraries/commerce/product/actions/fetchProductOptions.js
  libraries/commerce/product/actions/fetchProductProperties.js
  libraries/commerce/product/actions/fetchProductRelations.js
  libraries/commerce/product/actions/fetchProductShipping.js
  libraries/commerce/product/actions/fetchProductVariants.js
  libraries/commerce/product/actions/fetchProducts.js
  libraries/commerce/reviews/actions/fetchProductReviews.js
  libraries/commerce/reviews/actions/fetchReviews.js
  libraries/commerce/reviews/actions/submitReview.js
  libraries/common/actions/menu/fetchMenu.js
  libraries/common/actions/page/fetchPageConfig.js
  libraries/common/actions/user/fetchRegisterUrl.js
  libraries/common/actions/user/fetchUser.js
  libraries/common/actions/user/login.js
  libraries/common/actions/user/logout.js
Labels: internal

#921 Added reserve to cart user path.
  libraries/common/reducers/user/index.js
  libraries/common/reducers/user/location.js
  libraries/common/selectors/user.js
  libraries/engage/locations/action-creators/index.js
  libraries/engage/locations/action-creators/selectLocation.js
  libraries/engage/locations/action-creators/storeFormInput.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSheet/FulfillmentSheet.connector.js
  libraries/engage/locations/components/FulfillmentSheet/FulfillmentSheet.jsx
  libraries/engage/locations/components/StockInfo/StockInfo.jsx
  libraries/engage/locations/components/StoreList/StoreListProductVariants.connector.js
  libraries/engage/locations/components/StoreList/StoreListProductVariants.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListProduct.spec.jsx.snap
  libraries/engage/locations/constants/ActionTypes.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/helpers/createOrder.js
  libraries/engage/locations/reducers/index.js
  libraries/engage/locations/reducers/userFormInput.js
  libraries/engage/locations/reducers/userLocation.js
  libraries/engage/locations/selectors/index.js
  package.json
  themes/theme-gmd/pages/reducers.js
  themes/theme-ios11/pages/reducers.js
Labels: enhancement

#926 Log every console.error log into sentry.io
  libraries/common/actions/client/fetchClientInformation.js
  libraries/common/subscriptions/error.js
  libraries/core/constants/ErrorManager.js
  libraries/core/helpers/index.js
Labels: internal

#922 Added fulfillment location to the add to cart action from PDP if user location is selected.
  libraries/engage/locations/action-creators/index.js
  libraries/engage/locations/action-creators/storeFulfillmentMethod.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/constants/ActionTypes.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/index.js
  libraries/engage/locations/reducers/userLocation.js
  libraries/engage/locations/selectors/index.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/actions/index.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/CTAButtons/components/CartButton/index.jsx
  themes/theme-ios11/pages/Product/components/AddToCartBar/actions/index.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/connector.js
  themes/theme-ios11/pages/Product/components/AddToCartBar/index.jsx
Labels: enhancement

#930 Add "Direct Ship" cart items group
  libraries/engage/cart/cart.helpers.js
  libraries/engage/cart/components/CartItems/CartItemGroup.jsx
  libraries/engage/cart/components/CartItems/CartItemGroup.style.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.connector.js
  libraries/engage/cart/components/CartItems/CartItemGroupReservation.jsx
  libraries/engage/cart/components/CartItems/CartItemGroupShipping.jsx
  libraries/engage/cart/components/CartItems/index.js
  libraries/engage/cart/index.js
  libraries/engage/locations/constants/index.js
  libraries/engage/locations/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Cart/components/Content/index.jsx
  themes/theme-gmd/pages/Cart/components/ItemsGroup/index.jsx
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Cart/components/Content/index.jsx
  themes/theme-ios11/pages/Cart/components/ItemsGroup/components/FulfillmentLocation/connector.js
  themes/theme-ios11/pages/Cart/components/ItemsGroup/components/FulfillmentLocation/index.jsx
  themes/theme-ios11/pages/Cart/components/ItemsGroup/components/FulfillmentLocation/style.js
  themes/theme-ios11/pages/Cart/components/ItemsGroup/index.jsx
Labels: enhancement

#929 Reservation form validation
  libraries/engage/core/hooks/__tests__/useFormState.spec.jsx
  libraries/engage/core/hooks/useFormState.js
  libraries/engage/core/index.js
  libraries/engage/core/validation/__tests__/validation.hooks.spec.js
  libraries/engage/core/validation/__tests__/validation.spec.js
  libraries/engage/core/validation/index.js
  libraries/engage/core/validation/validation.hooks.js
  libraries/engage/core/validation/validation.js
  libraries/engage/locations/components/ReserveForm/ReserveForm.constraints.js
  libraries/engage/locations/components/ReserveForm/ReserveForm.jsx
  libraries/engage/package.json
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  yarn.lock
Labels: enhancement

#932 Extended the FulfillmentSelector with a button to change location when the pickup option is selected
  libraries/core/classes/Conditioner/index.js
  libraries/core/classes/Conditioner/spec.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.style.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorButtonChangeLocation.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/FulfillmentSelector.spec.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/__snapshots__/FulfillmentSelector.spec.jsx.snap
  libraries/engage/locations/components/FulfillmentSheet/FulfillmentSheet.jsx
  libraries/engage/locations/components/StockInfo/StockInfo.jsx
  libraries/engage/locations/components/StockInfo/StockInfoInventory.jsx
  libraries/engage/locations/components/StockInfo/__tests__/StockInfo.spec.jsx
  libraries/engage/locations/components/StockInfo/__tests__/__snapshots__/StockInfo.spec.jsx.snap
  libraries/engage/locations/components/StoreList/StoreAddress.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddress.spec.jsx
  libraries/engage/locations/helpers/getAvailabilitySettings.js
  libraries/engage/locations/helpers/index.js
  libraries/engage/locations/helpers/productInventory.js
  libraries/engage/locations/index.js
  libraries/engage/locations/reducers/userLocation.js
  libraries/engage/locations/selectors/__tests__/index.spec.js
  libraries/engage/locations/selectors/index.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: enhancement

#935 Show reservation cart errors
  libraries/core/classes/Conditioner/index.js
  libraries/engage/components/MessageBar/index.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelector.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorAddToCart.connector.js
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorAddToCart.jsx
  libraries/engage/locations/components/FulfillmentSelector/FulfillmentSelectorButtonChangeLocation.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/FulfillmentSelector.spec.jsx
  libraries/engage/locations/components/FulfillmentSelector/__tests__/__snapshots__/FulfillmentSelector.spec.jsx.snap
  libraries/engage/locations/subscriptions.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/pages/Cart/components/Item/style.js
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/pages/Cart/components/Item/style.js
Labels: internal

#933 Added product media section portal
  libraries/engage/components/constants.js
  themes/theme-gmd/pages/Product/components/Media/index.jsx
  themes/theme-ios11/pages/Product/components/Media/index.jsx
Labels: enhancement

#934 Made number of columns in ProductGrid configurable via theme config
  libraries/common/components/InfiniteContainer/__snapshots__/spec.jsx.snap
  libraries/common/components/InfiniteContainer/index.jsx
  libraries/common/components/InfiniteContainer/spec.jsx
  libraries/common/constants/DisplayOptions.js
  themes/theme-gmd/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-gmd/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-gmd/components/ProductGrid/components/Iterator/style.js
  themes/theme-gmd/components/ProductGrid/index.jsx
  themes/theme-gmd/extension-config.json
  themes/theme-ios11/components/ProductGrid/__snapshots__/spec.jsx.snap
  themes/theme-ios11/components/ProductGrid/components/Iterator/index.jsx
  themes/theme-ios11/components/ProductGrid/components/Iterator/style.js
  themes/theme-ios11/components/ProductGrid/index.jsx
  themes/theme-ios11/extension-config.json
Labels: enhancement

#936 Added widget config for ProductSlider to configure slidesPerView
  extensions/@shopgate-theme-config/frontend/config-common.js
  libraries/engage/product/components/RelationsSlider/RelationsSliderContent.jsx
  themes/theme-gmd/components/ProductSlider/index.jsx
  themes/theme-gmd/components/ProductSlider/spec.jsx
  themes/theme-gmd/extension-config.json
  themes/theme-gmd/widgets/ProductSlider/index.jsx
  themes/theme-gmd/widgets/ProductSlider/spec.jsx
  themes/theme-ios11/components/ProductSlider/index.jsx
  themes/theme-ios11/components/ProductSlider/spec.jsx
  themes/theme-ios11/extension-config.json
  themes/theme-ios11/widgets/ProductSlider/index.jsx
  themes/theme-ios11/widgets/ProductSlider/spec.jsx
Labels: enhancement

#937 Change location for reserve cart item
  .flowconfig
  libraries/commerce/cart/subscriptions/index.js
  libraries/common/helpers/config/mock.js
  libraries/engage/locations/components/Cart/CartItemProductChangeLocation.connector.js
  libraries/engage/locations/components/Cart/CartItemProductChangeLocation.jsx
  libraries/engage/locations/components/Cart/CartItemProductChangeLocation.types.js
  libraries/engage/locations/components/Cart/CartItemProductContextMenuItem.jsx
  libraries/engage/locations/components/Cart/index.js
  libraries/engage/locations/components/Fulfillment/Fulfillment.connector.js
  libraries/engage/locations/components/Fulfillment/Fulfillment.jsx
  libraries/engage/locations/components/Fulfillment/Fulfillment.style.js
  libraries/engage/locations/components/Fulfillment/Fulfillment.types.js
  libraries/engage/locations/components/Fulfillment/ProductLocations.connector.js
  libraries/engage/locations/components/Fulfillment/ProductLocations.jsx
  libraries/engage/locations/components/Fulfillment/ProductLocations.types.js
  libraries/engage/locations/components/Fulfillment/index.js
  libraries/engage/locations/components/StoreList/StoreListSearch.connector.js
  libraries/engage/locations/components/StoreList/StoreListSearch.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreListSearch.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListSearch.spec.jsx.snap
  libraries/engage/locations/components/index.js
  libraries/engage/locations/index.js
  libraries/engage/locations/subscriptions.js
  libraries/engage/product/hocs/withProduct.js
  libraries/engage/product/index.js
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/components/Title/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/components/Product/index.jsx
  themes/theme-gmd/pages/Cart/components/Item/index.jsx
  themes/theme-gmd/pages/Cart/spec.jsx
  themes/theme-ios11/pages/Cart/components/Content/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/components/QuantityPicker/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/components/Title/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/components/Layout/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/components/Product/index.jsx
  themes/theme-ios11/pages/Cart/components/Item/index.jsx
Labels: internal

#938 Applied UI tweaks to the StoreListAddress entries within FulfillmentSheet
  libraries/engage/locations/components/StoreList/StoreAddress.jsx
  libraries/engage/locations/components/StoreList/StoreAddressDistance.jsx
  libraries/engage/locations/components/StoreList/StoreAddressHeading.jsx
  libraries/engage/locations/components/StoreList/StoreAddressStoreDetails.jsx
  libraries/engage/locations/components/StoreList/StoreListProduct.jsx
  libraries/engage/locations/components/StoreList/StoreListProductAvailability.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddressDistance.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddressHeading.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/StoreAddressStoreDetails.spec.jsx
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressDistance.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressHeading.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressMailingAddress.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreAddressStoreDetails.spec.jsx.snap
  libraries/engage/locations/components/StoreList/__tests__/__snapshots__/StoreListProduct.spec.jsx.snap
  libraries/engage/locations/components/StoreList/style.js
  libraries/ui-material/Accordion/components/AccordionContent/index.jsx
  package.json
  themes/theme-gmd/babel.config.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-gmd/package.json
  themes/theme-ios11/babel.config.js
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
  themes/theme-ios11/package.json
  yarn.lock
Labels: enhancement

#940 Alert Shoppers if coupons of direct ship cart is removed.
  libraries/engage/locations/subscriptions.js
  themes/theme-gmd/locale/de-DE.json
  themes/theme-gmd/locale/en-US.json
  themes/theme-gmd/locale/es-ES.json
  themes/theme-gmd/locale/fr-FR.json
  themes/theme-gmd/locale/it-IT.json
  themes/theme-gmd/locale/nl-NL.json
  themes/theme-gmd/locale/pt-PT.json
  themes/theme-ios11/locale/de-DE.json
  themes/theme-ios11/locale/en-US.json
  themes/theme-ios11/locale/es-ES.json
  themes/theme-ios11/locale/fr-FR.json
  themes/theme-ios11/locale/it-IT.json
  themes/theme-ios11/locale/nl-NL.json
  themes/theme-ios11/locale/pt-PT.json
Labels: internal

#941 Added ProductHeader to themeApi
  themes/theme-gmd/themeApi/index.js
  themes/theme-ios11/themeApi/index.js
Labels: enhancement

#939 Introduced a className prop to the Media component of the themes to enable custom component widths via classes
  libraries/common/components/Swiper/styles.js
  libraries/engage/product/components/MediaSlider/index.jsx
  libraries/engage/product/components/ProductImage/__snapshots__/spec.jsx.snap
  libraries/engage/product/components/ProductImage/index.jsx
  themes/theme-gmd/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-gmd/pages/Product/components/Media/components/ProductMediaSlider/index.jsx
  themes/theme-gmd/pages/Product/components/Media/index.jsx
  themes/theme-ios11/pages/Product/components/Media/components/ProductImageSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/components/ProductMediaSlider/index.jsx
  themes/theme-ios11/pages/Product/components/Media/index.jsx
Labels: enhancement

#942 Clear babel cache when installing theme dependencies
  themes/theme-gmd/package.json
  themes/theme-ios11/package.json
Labels: enhancement

#944 The Availability component within the ProductInfo is now hidden when the product has fulfillment methods assigned
  libraries/engage/locations/subscriptions.js
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/connector.js
  themes/theme-gmd/pages/Product/components/Header/components/ProductInfo/index.jsx
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/connector.js
  themes/theme-ios11/pages/Product/components/Header/components/ProductInfo/index.jsx
Labels: enhancement
